### ISSUE TITLE
Changing the name of the repository

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#10]
Due to perceived interest from users (and myself), this project has kind of taken a turn from being centered around userContent tweaks to creating a universal dark theme for Firefox (about half the code posted here belongs in userChrome.css).

As such, I believe it would be fitting to change the name of this repository to better reflect its contents.  

As per https://help.github.com/articles/renaming-a-repository/ :

> When you rename a repository, all existing information, with the exception of Project Pages URLs, is automatically redirected to the new name, including:
> 
>     Issues
>     Wikis
>     Stars
>     Followers
> 
> In addition to redirecting web traffic, all `git clone`, `git fetch`, or `git push` operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:
> 
>  `git remote set-url origin new_url`

Therefore, there should be minimal side effects to anyone currently using/following this repository.  

If anyone has any thoughts, objections, reasons why this shouldn't be done etc., please let me know.

**Comment by tigerjack** [comment]
Don't know about the others, but maybe I can add a few thoughts.
I'm a Linux user and as such I use the default GTK theme for Firefox; indeed, apart from the `remove_white_flash` and `remove_bookmarks_bottom_border`, I don't use any other file in the `userChrome-files` directory, which actually causes a lot of strange behavior.

All of this is to say that I personally use your tweaks "just" to change the background color of otherwise unchangable Firefox directories and not as a global theme. So, maybe it could be interesting to have separate repositories for the tweaks only and for a global theme in general (which could of course use the tweaks repository).

Of course, these are just my 2 cents; I can just live with a global theme repo and copying/pasting only the files that I use.

**Comment by overdodactyl** [comment]
Thanks for the input - you bring up a really good point (and one I didn't really consider).

I should definitely come up with an easier/better way for users to select the global theme or just the `about` pages.

I will hopefully get that resolved soon, but in the mean time, as an alternative to copying and pasting it might be easiest to just remove the appropriate `@import` statements form the userChrome.css file (or, if you have a different userChrome file with your own tweaks, just put in the 2 appropriates `@import`'s

**Comment by helekron** [comment]
hey, love the theme! just installed it a couple days ago. so when you update this with changes, fixes, etc, do i have to re download all of it again or? (i had no idea what userchrome was up until earlier this week so this is all new to me)

**Comment by overdodactyl** [comment]
Hi @helekron -

I think the easiest approach to keeping up-to-date would be through the use of `git`.  

For installation, see here: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

If you're using the repository "as is", do the following:

Once you get it installed, use terminal to `cd` to your profile directory and use the following command:

`git clone https://github.com/overdodactyl/userContent-tweaks chrome`

This will copy the repository into your profile directory and name the folder `chrome`

To keep up to date, all you have to do know is `cd` to your `chrome` directory and use the command

`git pull`

I'll be setting up a wiki entry (hopefully soon) with more detailed instructions/various approaches. 

Hope this helps, let me know if there are any other questions.

**Comment by helekron** [comment]
thank you, this is exactly what i needed. looking forward to future changes!

**Comment by overdodactyl** [comment]
@tigerjack, are the recent changes to the repo enough to make your workflow easy, or would you still prefer to see two repos?

With `gulp`, I could add something like

```js
/* Remove White Flash and Bookmarks Border  */
gulp.task('userChrome_all', function() {
  return gulp.src(['userChrome-files/remove_white_flash.css', 'userChrome-files/remove_white_flash.css'])
    .pipe(concatCss('userChrome.css'))
    .pipe(gulp.dest('.'));
});
```

to `gulpfile.js` to create a `userChrome.css` file with the two modifications you use.
