### ISSUE TITLE
Rawgit.com CSS links 404ing

### ISSUE THREAD

**Issue by seascape** [overdodactyl/ShadowFox#100]
Under "code to add to webextension settings" on your [Altering webextensions page](https://github.com/overdodactyl/ShadowFox/wiki/Altering-webextensions) all three of the rawgit URLs currently 404 for me.

(In my case I am trying to retrieve the customization code for Violentmonkey.)

Thanks for a wonderful, cohesive, and modular dark theme!

**Comment by overdodactyl** [comment]
HI @seascape, thanks for letting me know! The file structure was getting a little out of hand as the project grew, so I had to rearrange things a bit.  In doing so, I forgot to update the links.  The wiki has been fixed, but here's the line for Violentmonkey:

```css
@import url("https://rawgit.com/overdodactyl/ShadowFox/master/css/webextensions/violentmonkey.css");
```

With the new scripts available, updating ShadowFox is quite a bit easier than it originally was.  As such, I'm wondering if there's still a large benefit to using the `@import` links from within the extension instead of just adding these changes to `userContent.css` like all the other extensions.  

Seems like keeping everything together might be a simpler/better approach to take now given the udpater scripts can find your UUIDs and grab the latest version from the repo.  

Any thoughts/opinions there as someone who's using the import links now?

**Comment by overdodactyl** [comment]
After giving it a little more thought, I think it would be best to move the code for these extensions to userConent.css with all the others.  

I think having them separated causes more confusion and unnecessary hassle than it does benefits.  

Additionally, having them in userContent will prevent having to load from GitHub and the presence of white flashes while the css loads.

**Comment by seascape** [comment]
I was sending you these exact thoughts via ESP. Glad they made it!

To respond a little to some of your queries, I already had a complex userChrome.css and a (relatively simple) userContent.css, so I was hesitant to run any scripts that might destroy the current stuff. I put ShadowFox in a subfolder and used four import statements to pull in ShadowFox's userChrome.css, userChrome_imports.css, userContent.css, and userContent_imports.css. Then I added UUIDs to a few of the userContent-files\webextension-tweaks files.

If the .vbs script can smoothly help me update this setup to later versions then that's cool!

**Comment by overdodactyl** [comment]
Given your use case, I think I would recommend the following:

* Move your chrome folder to a different location (the .vbs script should backup everything, but better safe than sorry if you have a bunch of stuff already)

* Add the .vbs script to your FF profile root directory and run it 

* Doing so will create a new chrome folder and download the latest versions of `userChrome.css` and `userContent.css` (you don't need the imports versions if you're using these).

* The script will create a directory inside the chrome folder titled `ShadowFox_customization`, which will contain four files:

    * `userChrome_customization.css`
    * `userContent_customization.css`
    * `internal_UUIDs.txt`
    * `color_overrides.css`

* Place any non-ShadowFox related userChrome tweaks (from your old userChrome) into `userChrome_customization.css`

* Place any non-ShadowFox related userContent tweaks (from your old userContent) into `userContent_customization.css`

* Place the UUIDs for any extensions into `internal_UUIDs.txt` in the following format:

`extensionName_UUID=internalUUID`

So, for example, lets say you have two extensions, uBlock Origin and Tree Style Tab.  In userContent.css, you'll see the strings to be replaced are `tree_style_tab_UUID` and `ublock_origin_UUID`.  Your `internal_UUIDs.txt` file should then contain two lines looking like this:

`
ublock_origin_UUID=72cc0bdd-b9ee-9d4a-b306-8d044cc4dd98
tree_style_tab_UUID=efb99b92-8e90-4041-a9a3-924049c1819a
`
Re-run the updater script and restart Firefox.

Now, anytime you run the updater script, the following will happen:

* Old userChrome/Content will be backed up

* Latest versions of userChrome.css and userContent.css get downloaded from the repo

* Any tweaks in `userChrome_customization.css` or  `userContent_customization.css` get appended to the end of the corresponding file.  This way, they always go into effect and in the case of duplicate rules, your custom ones override the ShadowFox ones.

* Insert any UUIDs from `internal_UUIDs.txt` into userContent.css.  As such, you won't have to manually do this any time you update.

**Comment by seascape** [comment]
I see, thanks for the detailed explanation! I may well do this.

Funny that we have to worry about all this just because Mozilla doesn't build in a proper dark theme itself. What year is this again?

**Comment by overdodactyl** [comment]
No problem, let me know if you run into any problems!  And sorry for any confusion.  I've been having to shift things around about in the project as it's grown/I've learned stuff myself. I really need to update the wiki documentation to reflect the changes...just haven't gotten around to it.  

I know FF is working on improving the dark theme, but who knows how long it'll take haha
