### ISSUE TITLE
[Request] Mind the Time Add-on Theme

### ISSUE THREAD

**Issue by lhindir** [overdodactyl/ShadowFox#101]
First of all, this is an excellent repo! I've been trolling r/FirefoxCSS infrequently for months and only just came across the 3-month-old post. I found the more popular r/Firefox post after a search afterward.

I'm requesting a theme for the [Mind the Time](https://addons.mozilla.org/en-US/firefox/addon/mind-the-time) add-on! It has a popup and a full summary page. It's a pretty lightweight add-on, so I don't think it would be too difficult to style, but I obviously don't expect you to make it a priority.

Might I also suggest adding a basic color styling guide to fit the theme's design language? That way it would be easier for users to make pull requests for new add-ons. It could be simply comments in the color variables file, or a wiki page with more detailed explanations.

**Comment by overdodactyl** [comment]
Glad you stumbled across the project @lhindir! 

I'll look at Mind the Time when I get a chance :) If it's a lightweight one, I'll probably be able to get to it soon.

That's a good suggestion for the color styling guide though!  I think that would help out a lot as well

**Comment by lhindir** [comment]
Sounds good! Looking forward to it.

**Comment by overdodactyl** [comment]
Styling for Mind the Time has been added.  If there's any issues with it, feel free to let me know.

Please keep in mind that since I don't use the extension, if problems arise, I won't know about it unless I am notified.
