### ISSUE TITLE
Remove white line from Edge of sidebar and navbar

### ISSUE THREAD

**Issue by mustaqimM** [overdodactyl/ShadowFox#103]
I installed ShadowFox and now have a white line showing on the [edge](https://i.imgur.com/QV7ErWD.png)

**Comment by overdodactyl** [comment]
These lines don't show up for me under macOS, so I'm adding the "help wanted" label in hopes someone can contribute a fix.

Please operating system and the version of Firefox you are using.

**Comment by mustaqimM** [comment]
I'm on Linux and Firefox Nightly

**Comment by overdodactyl** [comment]
Which grey line are you referring to?

**Comment by mustaqimM** [comment]
@overdodactyl I'm talking of ![this](https://i.imgur.com/Z8BzmfE.png), to the left and top of the blue selected tab

**Comment by overdodactyl** [comment]
Interesting...not seeing that here no matter what TST theme I use. Is it possible you have any other custom styling effecting that?

You could try and offset it by adding something like this to the extra rules section of the TST preferences:

```css
.tab {
    margin-left: -4px !important;
}
```

**Comment by mustaqimM** [comment]
@overdodactyl That border seems to be part of the sidebar rather than TST, see ![here](https://i.imgur.com/Ckobtz2.png)

**Comment by overdodactyl** [comment]
Hmm.  Does that border show up on all sidebars?  For example, if you switch to the uBO logger does it it have that border still or does it look like this:

![ubo_logger](https://user-images.githubusercontent.com/33071129/37847917-5e390ada-2eca-11e8-8660-056bc127ec62.png)

?

**Comment by mustaqimM** [comment]
@overdodactyl It still shows on all, here's a better view of [it:](https://i.imgur.com/ObEUdqd.png)

**Comment by overdodactyl** [comment]
Are you using any other custom css, made any modifications to ShadowFox, or have other css files in your chrome folder?  Your screenshot looks very different than what I'm seeing in Firefox Nightly (header color, black background, blueish separator lines etc.):

![sidebar](https://user-images.githubusercontent.com/33071129/37848996-f39106a2-2ecd-11e8-941e-204d8b160fd9.png)

**Comment by mustaqimM** [comment]
@overdodactyl This is on a completely new install ![install](https://i.imgur.com/tpYOMky.png). I had as a black background because I wanted TST to be black.

**Comment by mustaqimM** [comment]
@overdodactyl Nightly updated and now it perfect

**Comment by mustaqimM** [comment]
@overdodactyl both

**Comment by nath1as** [comment]
the issue persists on nightly 63
