### ISSUE TITLE
Styling of snippets (Mozilla anoncements at bottom of start page)

### ISSUE THREAD

**Issue by batisteo** [overdodactyl/ShadowFox#104]
![screenshot from 2018-03-29 10-43-39](https://user-images.githubusercontent.com/2727048/38079474-4a0ae0be-333f-11e8-893a-1a40125255e5.png)

**Comment by overdodactyl** [comment]
Thanks @batisteo! Should be fixed

**Comment by batisteo** [comment]
Perfect, thanks!!
