### ISSUE TITLE
[Request] GreaseMonkey

### ISSUE THREAD

**Issue by DukeValentine** [overdodactyl/ShadowFox#105]
[vokoscreen-2018-03-30_01-11-50.zip](https://github.com/overdodactyl/ShadowFox/files/1862656/vokoscreen-2018-03-30_01-11-50.zip)

When I click on the toolbar icon, the options' font contrast is really bad unless I hover over them. According to the webextension list  ViolentMonkey is supported, but GreaseMonkey is not. If possible, I would be grateful if GreaseMonkey was added to the list.

**Comment by overdodactyl** [comment]
Hi @DukeValentine, I just downloaded Greasemonkey and I'm not seeing the lack of contrast you mentioned.

![gm](https://user-images.githubusercontent.com/33071129/38144057-c2d2ea66-3432-11e8-81ff-c3bf38b56d14.png)

Is it possible you have some other code that's effecting it?

I'll get to adding a dark theme for it when I get the chance, but no guarantees on when that may be.  

If you're up for trying something new, I'm a big fan of Violentmonkey.  I much prefer the UI and it's an open source project, which is always a plus in my books :)

**Comment by overdodactyl** [comment]
Styling for Greasemonkey has been added.  If there's any issues with it, feel free to let me know.

Please keep in mind that since I don't use the extension, if problems arise, I won't know about it unless I am notified about it.
