### ISSUE TITLE
Tracking Firefox's built in dark theme

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#108]
Firefox is starting to make some improvements to the built-in dark theme.  This issue will be used to track Firefox's progress and discuss the future directions of ShadowFox as these features are implemented.

### New features:

🔻 FF61

***Note:*** Unless uplifted, these changes will *not* make it into the next ESR cycle

- Panels (navbar menus, drop downs, browser notifications etc.)
- Awesome bar and search bar drop down
- New tab page

### Opinions on the new thememing:

The new themeing is still a little rough around the edges, but that's somewhat to be expected as they are only available in the Nightly channel at the time of writing this - hopefully there will be improvements on the way.

I'm not a huge fan of some of some of the color choices, mainly the choice to use pure black for panels and drop downs.  Personally, I think they look a little out of place given the color of the navigation bar:

![panels](https://user-images.githubusercontent.com/33071129/38278530-f1c7693a-378b-11e8-927f-6f9158f6de38.png)

Same goes for the awesome bar drop down.  Additionally, I think having the "one-off" search engines as a lighter color draws your eye towards them instead of the results, which is the natural place to look:

![awesome_bar](https://user-images.githubusercontent.com/33071129/38278567-212bb3c0-378c-11e8-97d0-ced51a97585b.png)

 ### Possible discussion topics:

- Future direction of ShadowFox.  Namely, what should be done with features that are now styled by Firefox?

- ???

I'll continue to update this thread, but if anyone has any opinions/thoughts/concerns etc., feel free to comment below.  Otherwise, I'll move forward with whatever I feel is best.

**Comment by stonecrusher** [comment]
I've also noticed Mozilla's plans and welcome them. Nonetheless I think you don't need to worry about ShadowFox. It'll take ages for them to release a complete dark skin - if it will ever be dark *everywhere*...

**Comment by overdodactyl** [comment]
Looks like the some of the issues I had with the menus and address bar drop downs has been partially addressed:

![ffn_menus](https://user-images.githubusercontent.com/33071129/38637218-fd48790a-3db9-11e8-9290-c9f5f04450f0.png)

**Comment by lhindir** [comment]
@overdodactyl The built-in dark theme is becoming more and more comprehensive. I now only import:
- `color_variables.css` (in both `userChrome.css` and `userContent.css`)
- `remove_white_flash.css`
- `secure_connection_colors.css`
- `about_pages.css`
- `amo_store.css`
- `directory_listings.css`
- `manifest.css`
- `raw_githubusercontent.css`
- and `view_source.css`

This set seems to pretty much do the trick for me these days.

Re: Future direction of ShadowFox, have you considered paring down ShadowFox with respect to the native dark theme? The import statement system is good, but it could be time to cut some code for all users. The small triangular element that is above menu popups is broken for me with ShadowFox, and the sidebar splitter is different than normal. Perhaps these still work on Mac, but they don't seem to work on Linux or Windows. I'm guessing the native theme will maintain better cross-platform support. I still love ShadowFox for theming about:pages, the AMO store, and add-ons, but perhaps its scope could be reduced which would make it easier to maintain?

Furthermore, I'm a little confused by the common files. Could you describe them? The only one that seems obvious to me is `color_variables.css`. Why do the other four need to be imported by both `userChrome.css` and `userContent.css`? `radios_checkboxes.css` doesn't seem to do anything on Linux, and the names of `library.css` and `trees.css` are confusing. I think `trees.css` is dropdown items?

Thanks for your work and for any insight you can provide!

**Comment by overdodactyl** [comment]
Hi @lhindir - thanks for bringing up the concerns/thoughts here.

>Re: Future direction of ShadowFox, have you considered paring down ShadowFox with respect to the native dark theme?

Yes, it's definitely been on my mind and something I've been wanting to do.  The goal of ShadowFox from the beginning was to be a supplemental tool to Firefox's default theme, not to style/re-style everything.  I've been pretty busy over the last couple months moving to a new state and starting up a new job, so unfortunately I haven't been able to put as much time into this project as I would like.  Pairing down on the code here would certainly help with maintenance, compatibility and future-proofing.  

I'm also thinking of trying to simplify the workflow/build process in hopes of making it easier for others to contribute.

The common files are features that can be used either by user userContent or userChrome.  `trees.css` are the list like items such as about:config entries, but also pop up in places like about:settings. Same kind of thing for radio boxes (some are in settings pages and menus, others in dialogues such as page settings).  Most people access the library through the menu bar, but some also open it in a tab using the url `chrome://browser/content/places/places.xul`, so it's included in both userChrome and userContent.
