### ISSUE TITLE
Visited link colour

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#109]
I think I remember to have seen the same problem also somewhere in the FF options, but not sure where.

Here I found an example: Visited links are dark purple on dark grey and therefore not readable.
![screenshot 114](https://user-images.githubusercontent.com/1388389/38439776-3e8fb0e2-39df-11e8-8efa-a0ce1302d623.png)

`FF 59.0.2 (64-Bit)`, latest ShadowFox

**Comment by overdodactyl** [comment]
Thanks! Should be fixed now and the buttons are styled as well.

**Comment by stonecrusher** [comment]
Thank you for the fast fix!
And I am surprised how many changes were necessary o.O

**Comment by overdodactyl** [comment]
No problem! Appreciate ya opening up the issue.  

If you stumble across any other links like this just let me know.
