### ISSUE TITLE
Link for the tweaks for extensions?

### ISSUE THREAD

**Issue by tkhquang** [overdodactyl/ShadowFox#111]
https://github.com/overdodactyl/ShadowFox/tree/master/webextensions

This link seems to be broken, how can I find the tweaks now?

**Comment by overdodactyl** [comment]
Code for all webextension tweaks can now be found in the [`webextension-tweaks`](https://github.com/overdodactyl/ShadowFox/tree/master/css/userContent-files/webextension-tweaks) directory and should be applied via `userContent.css`.
