### ISSUE TITLE
Documentation lacks uninstallation instructions

### ISSUE THREAD

**Issue by martyschaer** [overdodactyl/ShadowFox#112]
I'd like to uninstall ShadowFox and get back to default behaviour of Firefox. The documentation doesn't mention uninstallation. How can I uninstall it?

**Comment by overdodactyl** [comment]
I quickly threw together some info here:

https://github.com/overdodactyl/ShadowFox/wiki/Uninstallation

If you have any questions or there's any confusion, just let me know and I'll update the documentation accordingly.

**Comment by martyschaer** [comment]
Thank you so much!

**Comment by theSdev** [comment]
> 
> 
> I quickly threw together some info here:
> 
> https://github.com/overdodactyl/ShadowFox/wiki/Uninstallation
That does not exist anymore. Is there a guide for uninstallation? 
Thanks.

**Comment by theSdev** [comment]
> 
> 
> I quickly threw together some info here:
> 
> https://github.com/overdodactyl/ShadowFox/wiki/Uninstallation

That page does not exist anymore. Any guides for uninstallation?
Thanks.

**Comment by overdodactyl** [comment]
If you're using the installer/updater script, you can simply use the "uninstall" button.

Otherwise just delete any files you added to your `chrome` folder.

In either case, you will have to restart Firefox.
