### ISSUE TITLE
Violentmonkey popup body is not styled

### ISSUE THREAD

**Issue by Zlewness** [overdodactyl/ShadowFox#114]
* Violentmonkey
* Nightly
* Windows 7
* I've got the rest of the userContent style working just fine on all the pages and the rest of the popup but the 'body' part of the popup is not being styled. Since I'm not using the userChrome parts of the style it would be useful if you could point to me the line in that file that handles this part.
* screenshots:
![untitled](https://user-images.githubusercontent.com/31130616/38515670-6b0a5522-3c24-11e8-860a-7adad19a2245.jpg)

**Comment by overdodactyl** [comment]
Thanks for the heads up! Looks like their most recent update broke the styling.  

Check here for the source:

https://github.com/overdodactyl/ShadowFox/commit/ffea7697d6bc7f8a117a383086f192daa72b4c5a
