### ISSUE TITLE
Updating the Windows updater script

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#117]
Hi everyone,

There have been some updates to the mac and linux updater scripts that have not yet been implemented in the Windows version, namely:

* Having the option to automatically find internal UUIDs and generate internal_UUIDs.txt using `internal_UUID_finder.sh`

* Script auto-updates itself based on version number

* Being able to use the updater script from any path (this has *not* yet been put in the Linux version) #115 

    * If updater is in a Firefox profile directory, will update there

    * If not:

        * If there's only one profile, update in it

        * If there's multiple, let user choose

I would greatly appreciate any help implementing these changes in `ShadowFox_updater_windows.vbs`, as I don't have Windows to write/test on, and I'll do as much as I can to assist.

Thanks!

@CarlColijn, is this something you would have time/interest in doing?

**Comment by CarlColijn** [comment]
I'm on it :)

**Comment by CarlColijn** [comment]
And already got a question / suggestion: you opted to have the installer script download the latest "internal_UUID_finder.sh" file, mark it as executable, and in turn run that.  However, as I see it, the only non-static part in that file is the UUID mappings.  Would it not be better to merge the code from that file into the installer script, and only download the latest UUID mappings as plain data?

The benefit would be to split data from code (cleaner), we wouldn't have to run secondary scripts, and (on Windows at least) we wouldn't even need to actually save the UUID mappings and/or update script file.

I don't know if this causes more trouble than it's worth for Linux / Mac, though...

**Comment by overdodactyl** [comment]
Thanks for helping with this @CarlColijn!!

I agree, it would be nice to split out the UUID mappings from the updater scripts.  I was actually thinking about this last night as well.  I think it might be nice to have a file named `webextension_mapping.txt` or something of that nature in the following format:

```
tridactyl.vim@cmcaine.co.uk|tridactyl
uBlock0@raymondhill.net|ublock_origin
uBO-Scope@raymondhill.net|ubo_scope
uMatrix@raymondhill.net|umatrix
```

In the future, this format could be then expanded to solve problems such as #110 - where it would be nice to "force" users to have fixes for certain webextensions that have compatibility issues in `about:addons`, while still leaving others as a choice.  We could use something like:

```
tridactyl.vim@cmcaine.co.uk|tridactyloptional
uBlock0@raymondhill.net|ublock_origin|required
uBO-Scope@raymondhill.net|ubo_scope|both
uMatrix@raymondhill.net|umatrix|optional
```

I still haven't figured the best way to approach that problem though, so I don't want to get to far ahead of myself...it would just be nice to have a format that could be expanded with additional options need be.  


I'm not sure if you were thinking of removing `internal_UUIDs.txt`, but I think that is still worth keeping, however (for more discussion on that, see #84).  

Additionally, adding the content of `internal_UUID_finder.sh` directly to the updaters would be worthwhile.  For those who are using ShadowFox through a method other than the updater scripts, it might be nice to keep it in the repository, however.

**Comment by overdodactyl** [comment]
I've introduced the format brought up here and combined the mac updater and the UUID finder scripts (haven't yet done so in the linux version)

**Comment by SrKomodo** [comment]
I guess this can be closed now?

**Comment by overdodactyl** [comment]
Yep! Thanks
