### ISSUE TITLE
Hard-coded profile folder path

### ISSUE THREAD

**Issue by CarlColijn** [overdodactyl/ShadowFox#118]
When updating the Windows installer script to include the latest Linux/Mac functionality, I saw that you have hard-coded the main path to the profile folder (to determine where to run).  My FireFox however has been configured to use a different location for the profile (not in the default location under "%APPDATA%\Mozilla\FireFox\Profiles", but on a 2nd drive).

In my case the "Profiles" folder there is thus empty, but there's a "profiles.ini" file next to the "Profiles" folder, in which are listed all profiles.  I can't remember if this profiles.ini file will also list all profiles when they are still in their default location, but I assume it would.

If such a file also exists under Linux / Mac, then it might be nice to make use if it.  However, I wonder how many people actually override their profile paths...

The content of mine is:

```
[General]
StartWithLastProfile=1

[Profile0]
Name=MyProfile
IsRelative=0
Path=D:\App data\FireFox\Profile~
Default=1
```

so it would be easy to parse out the paths to all known profiles.  It also ties in a user-set name to the profile folders found, which is nice to use when asking which profile to update.

**Comment by CarlColijn** [comment]
I've dug into this a bit more, but it seems "profiles.ini" is also present on Linux & Mac.  Documentation for it can be found at the [MozillaZine website](http://kb.mozillazine.org/Profiles.ini_file).  I think I'll let the Windows installer use it, if only because it would make testing & developing the Windows installer script actually possible for me :)

**Comment by CarlColijn** [comment]
... and to finish it off: I've updated the Windows updater to be able to run from anywhere and asks the user for the profile to update if there's more than one.  It'll also deal with profiles located in non-relative locations.  It was too nice (and too impractical for me personally) not to implement - couldn't resist!

The changes will come along with the pull request I'll send when I've finished the backlog :)

**Comment by SrKomodo** [comment]
I have been following this discussion for a while now, and I think the best solution would be to ditch the current updater scripts and replace them with a cross-platform program.

I have been toying with writing a Golang program for this, but I can't promise anything yet. I will keep you guys informed.

**Comment by overdodactyl** [comment]
Thanks for looking into this more @CarlColijn! I did have the profile path hard coded simply because I didn't think of other use cases such as you described (I haven't even heard of `profiles.ini`).

I'll look into that a bit more and try and accommodate that use case for the mac/linux updaters as well. I appreciate you doing it for the WIndows one!

**Comment by overdodactyl** [comment]
@SrKomodo, I think you're right that it would be ideal to have a cross-platform solution.  

I had originally considered using python, but I was a little worried about the number of people who would already have python installed on their computer.  I ultimately went with the bash/vbs scripts because it was a native solution people wouldn't have to download extra software to use.

I'm not very familiar with Golang, but I'm always open to looking into new things.

**Comment by CarlColijn** [comment]
On Windows you'd indeed have a hard time finding Python installed.  I have, but then you'd also have to consider the Python v2 vs. v3 issue.  You could however still use Python as a development language; there are compilers for Windows which make a single executable from the Python script, though I have no experience with them.  Golang on the other hand seems to be able to cross-compile to Windows, Mac and Linux as well, so might also be a good option.

**Comment by overdodactyl** [comment]
Looks like it is cross-platform, but you would still need to download/install it, no?  In which case, would it much more beneficial than python?

**Comment by overdodactyl** [comment]
On a slightly random note, if either of you guys (or anyone else for that matter) use/prefer Slack for communication, you're welcome to join the ShadowFox workspace ([invitation link](https://join.slack.com/t/shadowfox-workspace/shared_invite/enQtMzI5Nzk5OTk1MjcxLThkMDgwOGE5ZDY1MDUyNjIwNWQ2MTlmMjEwZTJiZmZjYTUxODM4ZTRkNzhiNGRhZTFhMjdjMTFjMTQ3YjZjYzU)).

**Comment by SrKomodo** [comment]
Thankfully Golang cleanly compiles to native executables for each OS, so we can be sure that it would run on all platforms @overdodactyl.

I actually had this idea on my backlog from quite a while, and I do have a prototype already made, but it is very outdated now compared to the updater scripts so I will have to make several changes.

Once i have a working program with the same features as the updater script, I will upload it to it's own repo so that we can test it before making it official.

**Comment by overdodactyl** [comment]
>Thankfully Golang cleanly compiles to native executables for each OS, so we can be sure that it would run on all platforms

Oh perfect, that sounds really promising then! 

If you want me to add another branch to this repo for testing the script or if there's anything else I can do to help just let me know.

**Comment by CarlColijn** [comment]
The Golang option (or an alternative Python one e.g.) indeed seems like the better one, so I think it should be done.  As long as it's a statically linked executable that doesn't need installation.  Point to consider though is, since it's an executable, if it needs to be signed with a digital certificate to not scare users away on the Windows platform.

Could you give a (very) rough estimate on when you think the Golang version can go live, since I wonder if it is still wise for me to put effort into updating the Windows script, if the Golang version is up for testing soon...  I'll at least send a pull request with the working changes I have made so far.

Unfortunately I have no experience in Go, so I won't be able to help out there.  (Could test out the Windows binary though.)

**Comment by SrKomodo** [comment]
I am having a busy schedule right now, but I think that by about next week the program will have feature parity with the updater scripts @CarlColijn.

**Comment by overdodactyl** [comment]
@SrKomodo, just as a heads up, I think the only other change that would be coming to the mac/linux updater scripts soon (other than incorporating access to `profiles.ini` mentioned here) would be the idea brought up in #117.  Namely, that the UUID mapping should be moved to an independent file (https://github.com/overdodactyl/ShadowFox/issues/117#issuecomment-380552450).
