### ISSUE TITLE
White border around bookmark scroll buttons

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#124]
This issues was reported to me via Reddit:

The scroll buttons in the bookmarks submenu has a white border, but the top level does not:

![scroll](https://s26.postimg.cc/82t27nomx/shadowfox_bug.png)

Scroll buttons were styled in 9aa5aa8. 

If anyone who has Windows could investigate this, I would really appreciate it (pinging @loopy750 if you have the chance).

**Comment by loopy750** [comment]
Hey there, looking quickly, this seems to do the trick. Unsure as yet if it affects/breaks anything else.

```
.popup-internal-box {
	background-color: var(--grey-60) !important;
}
```

**Comment by overdodactyl** [comment]
Thanks for the quick reply!

The only references to `.popup-internal-box` I'm seeing in `global.css` are to with regards to the `.autorepeatbutton`s, so I'm guess there wouldn't be any side effects. 

Does 

```css
#BMB_bookmarksPopup .popup-internal-box {
	background-color: var(--grey-60) !important;
}
```

still do the trick?  It might be good to add more specificity if we're not sure what else it might effect.

**Comment by loopy750** [comment]
Yep, that's still good. Been a while since I've looked at the code, as I'm usually also specific like that.

**Comment by overdodactyl** [comment]
Perfect, thanks for the help!
