### ISSUE TITLE
Isn't webextension_mappings.txt unnecesary?

### ISSUE THREAD

**Issue by SrKomodo** [overdodactyl/ShadowFox#126]
I don't fully understand the purpose of webextension_mappings.txt.

For example, instead of having to write `violentmonkey_UUID` in the css and then adding `violentmonkey|{aecec67f-0d10-4fa7-b7c7-609a2db280cf}` to the mappings, why can't we just use `{aecec67f-0d10-4fa7-b7c7-609a2db280cf}` in the css?

(By the way, the Go updater script is basically done except for the UUIDs, and I just wanted to get this cleared up before implementing it)

**Comment by overdodactyl** [comment]
Originally there were a couple reasons for it.  As the scripts/structure of the repo changed a bit though I think it's become a little less important. I think the only real benefit it has now is that it makes for a convenient way to use `add_UUIDs.sh` and `remove_UUIDs.sh`.  These scripts are helpful for users utilizing `userChrome.css` and `userContent.css` (the file name to replace in can be determined by shorthand - e.g. `violentmonkey_UUID` -->  `violentmonkey.css`).  

I guess another plus is it makes it clear in internal_UUIDs what each is for in case a user wants to remove one.


That being said, I think it might be a good idea to shift away from this method and simply do what you are suggesting.  It would be easier for me to add new extensions, and wouldn't be necessary to download `webextension_mappings.txt` on every update.

**Comment by overdodactyl** [comment]
Would it help if I created a new branch of the repo with, for example, `{aecec67f-0d10-4fa7-b7c7-609a2db280cf}` instead of `violentmonkey_UUID`?

**Comment by SrKomodo** [comment]
As i said on #127 I already made a fork of the repo with those changes
