### ISSUE TITLE
Handling user customizations on uninstall

### ISSUE THREAD

**Issue by CarlColijn** [overdodactyl/ShadowFox#133]
When uninstalling with the new installer (v. 1.2) it only removes files it has itself created, but user customizations from the "ShadowFox_customization" folder also disappear (or rather, the whole folder gets removed, incl. any extra files you put in there).

It would be better to either:
- add a settings file in the chrome folder which lists which files the installer app added, and only remove those, but that way user-generated changes to any of these files will not be noticed, or
- only remove the files if they are still zero bytes large, and keep them if they're filled, and
- only remove the individual files created by the installer and leave any other files in place, only removing the parent folder if it's empty afterwards.

**Comment by SrKomodo** [comment]
Would it be a good idea if `ShadowFox_customization` wasn't deleted when uninstalling? Not only would it solve all of those problems you mentioned, but also keeping the folder there isn't doing any harm

**Comment by t2YU2m8l83** [comment]
This would also be fixed if "bug" #130 would be considered. I still belive adding a single @import statement to the original userChrome.css/userContent.css would be the best installation way for the theme. That way you can simply delete the whole ShadowFox folder and user customisations would be retained.

**Comment by overdodactyl** [comment]
I don't have any strong preferences here, so whatever you guys think is best/is easiest to implement is good with me.  

My initial feeling would be to lean away from using a config file though.  @CarlColijn's second option sounds pretty good, but if that's too much of a hassle to incorporate I think leaving the whole folder is fine.
