### ISSUE TITLE
RSS Pages

### ISSUE THREAD

**Issue by t2YU2m8l83** [overdodactyl/ShadowFox#138]
While they're technically not part of FF themself, all RSS-pages follow the same desgin and should receive a dark theme. My old dark theme for FF had them styled.

**Comment by t2YU2m8l83** [comment]
Yes.

**Comment by overdodactyl** [comment]
Just add a theme for it...feel free to let me know if you run across any problems.

**Comment by overdodactyl** [comment]
I've fixed the media content box and the subscribe button, but I'm not seeing the white box at the top of the screen.  Are you using a userstyle via Stylus or something of that nature for that site?

![rss2](https://user-images.githubusercontent.com/33071129/39828634-49674940-53ab-11e8-8c47-a30380e57f8c.png)

**Comment by t2YU2m8l83** [comment]
I use custom styles but they're all wrapped inside @-moz-document and won't affect other pages.
I've looked into the problem myself and the following snippet results in the same look as your image (except the dropdown/checkbox/rss icon which should be system defaults)

```
#feedHeaderContainer{
	background-color: var(--in-content-box-background) !important;
	display: inline-block !important;
}
#feedHeaderContainerSpacer{
	display: none !important;
}
div.entry a[href]{
	color: var(--in-content-link-color) !important;
}
div.entry a[href]:hover{
	color: var(--in-content-link-color-hover) !important;
}
div.entry a[href]:active{
	color: var(--in-content-link-color-active) !important;
}
div.entry a[href]:visited{
	color: var(--in-content-link-color-visited) !important;
}
```

**Comment by overdodactyl** [comment]
Thanks for looking into it! I'll get those fixes incorporated.
