### ISSUE TITLE
Issues with Colouring on Mozilla Homepage

### ISSUE THREAD

**Issue by DakotaGunter** [overdodactyl/ShadowFox#139]
Browser Version: Firefox Nightly Version 61.0a1
OS: Windows 10
Go to https://www.mozilla.org/
Screenshot: https://screenshots.firefox.com/ZZXoPGI2MOf8TPV1/www.mozilla.org
Used installer to install ShadowFox

**Comment by overdodactyl** [comment]
I can't reproduce on my end. Is it possible you have an extension or something of that nature effecting it? Maybe it's picking up variables defined in ShadowFox?

**Comment by DakotaGunter** [comment]
Just reinstalled SF. I no longer have the problem

**Comment by overdodactyl** [comment]
Thanks for the update
