### ISSUE TITLE
Need help changing the url drop down color

### ISSUE THREAD

**Issue by ChronoVlad** [overdodactyl/ShadowFox#141]
Screenshot: https://i.imgur.com/7qeliqX.png

As seen in the screenshot i wanna change the blue default color to black since its hard for me to read the text.

**Comment by overdodactyl** [comment]
Hi @ChronoVlad, I would tend to agree that the selected text isn't easy enough to see.  I've brightened it up, but if that's not enough or not the solution you are looking for, you can add the following to your `userChrome_customization.css` file, run the updater script and restart firefox:

```
.autocomplete-richlistitem[selected=true],
.searchbar-treebody::-moz-tree-row(selected) {
  background-color: black !important
}
```

https://github.com/overdodactyl/ShadowFox/wiki/Customization
