### ISSUE TITLE
I want to add the exception (context_menus), it doesn't work, issue trying "Development" steps

### ISSUE THREAD

**Issue by EpamiTut** [overdodactyl/ShadowFox#142]
Hi overdodactyl and people.
Greetings, Great work.

Browser version: Firefox Quantum 59.0.2 (64-bit)
OS: Linux Mint 17.3 - Mate desktop (64-bit) - (ubuntu based).
How I am using ShadowFox: chrome directory on Firefox profile »» files: userChrome.css , userContent.css , userChrome_imports.css , userContent_imports.css

ShadowFox works, but I want to use exceptions ex: context_menus, but this doesn't work to me:
I added the text line --> @import "ShadowFox/userChrome_imports.css";
to the top of userChrome.css file located directly in the chrome folder.
I commented out on "userChrome_imports.css" file, the line thus: #//@import "css/userChrome-files/context_menus.css";

Step 1: I installed node.js v8.x through code line on https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
I cloned the repository (step 2 Development) to /home/name-user directory.
I'm trying to use this method steps 2 to 5 on https://github.com/overdodactyl/ShadowFox/wiki/Development , but I don't understand.
Could you explain these steps more precisely?
The way of installing the packages mentioned there (npm, gulp's..., ¿gulp task??)
Where these should be installed?, some require root rights (How to use the environment variables? For root or for my user?, ex: sudo -i, sudo -s)

Step 5, it mentions an example, something about gulpfile.js and code lines that I don't know they refer to.

I want to exclude the context_menus. Because, I use a Linux theme that include another context menus.
Excuse me my lexicon and ignorance.

I appreciate your kind attention.

P.S.: I attached the Alerts log installing npm, gulp's, ie steps 3, 4 of ShadowFox Development.
[Alerts installing Gulp's npm.txt](https://github.com/overdodactyl/ShadowFox/files/1978698/Alerts.installing.Gulp.s.npm.txt)

Thank you.

**Comment by overdodactyl** [comment]
Before going down the development path, let's see if we can get the `imports` method to work.  Is the `userChrome.css` file you mentioned and placed `@import userChrome_imports.css` atop of the ShadowFox one, or your own?

**Comment by EpamiTut** [comment]
Well, my chrome folder is: /home/name-user/.mozilla/firefox/xxxxxxxx.name-profile/chrome

Inside userChrome.css file pasted there from ShadowFox folder (currently 24/april/2018 date), I added the text --> @import "ShadowFox/userChrome_imports.css"; (after i modified this to --> @import "userChrome_imports.css";)
to the top of this userChrome.css text code.
And after, commenting out the corresponding line on "userChrome_imports.css" file, as I said before.
I don't know if gulp's and npm were well installed. Log in previous reply.

I'm not using the Updating method to ShadowFox via script.

**Comment by overdodactyl** [comment]
If you want to use the `userChrome_imports.css` version, you can't use the normal `userChrome.css`.  `userChrome.css` is simply a concatenated version of all the userChrome files found within the css/userChrome-files directory.  You can download the entire `css` directory from the repo (or use a git clone), then change the name of `userChrome_imports.css` to `userChrome.css` and comment out any lines you want.

**Comment by overdodactyl** [comment]
Did you get things worked out @EpamiTut?

**Comment by EpamiTut** [comment]
Hi overdodactyl.
Excuse me, my lateness
Currently, I am using the file `userContent.css`; and as `userChrome.css` I am using the file `remove_white_flash.css` renamed, they pasted in "chrome" folder.

Thanks.
