### ISSUE TITLE
Ublock does not theme black as the screenshots show

### ISSUE THREAD

**Issue by ChristoferMinestar** [overdodactyl/ShadowFox#144]
Ublock is still completely white, as the title stated. 
Using latest Ublock and Firefox Quantum 59.0.3 64bit, Windows 10 Version 10.0.17134 Build 17134.

Other than that, I am GLAD I discovered this by accident, it is AMAZING! Mainly the new tab page is great!
Edit: Screenshots
![image](https://user-images.githubusercontent.com/17222512/39789705-84e9f460-52ff-11e8-84ab-1820594b3bbb.png)

**Comment by overdodactyl** [comment]
Hi @ChristoferMinestar, I'm glad you stumbled across the project!

How did you install ShadowFox?  If you used the available installation/updater scripts, did you make sure the "Auto-Generate UUIDs" buttons was checked?

**Comment by 5HT2** [comment]
Yeah, I just opened the installer, selected install and hit enter. Did not
mess with any default settings

**Comment by SrKomodo** [comment]
The "Auto-Generate UUIDs" checkbox is disabled by default. Just run the installer again, check the box, and install again.

**Comment by 5HT2** [comment]
Thanks!
