### ISSUE TITLE
[Request] Dark Theme for Random User-Agent  & Privacy Possum

### ISSUE THREAD

**Issue by AldegarDespoina** [overdodactyl/ShadowFox#145]
Links:
https://addons.mozilla.org/en-US/firefox/addon/random_user_agent/?src=search
https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/

What needs to be themed: 
The white parts in this following screenshots:
https://i.imgur.com/F6K5nET.png
https://i.imgur.com/5qEbGd7.png

**Comment by overdodactyl** [comment]
I've added styling for both...let me know if that includes everything.

Please keep in mind that since I don't use either of these extensions, I likely won't know about any updates that break the styling unless I am notified of it.

**Comment by AldegarDespoina** [comment]
I'm sorry but where do i apply the codes? do i also need create additional .css?

**Comment by overdodactyl** [comment]
You can run the updater script again, just ensure you check the button "Auto Generate UUIDs", then restart Firefox

**Comment by AldegarDespoina** [comment]
Thank you so much! the codes worked fine.

**Comment by overdodactyl** [comment]
No problem, glad to hear it works!
