### ISSUE TITLE
[Bug] uMatrix and uBlock Origin

### ISSUE THREAD

**Issue by t2YU2m8l83** [overdodactyl/ShadowFox#146]
The "My rules" tab inside the uBlock Origin and uMatrix plugins randomly switches to the correct dark theme and the default theme. To reproduce, simply switch around the tabs and somtimes if you select the "My rules"-tab it won't load the the dark theme.
![umatrix](https://user-images.githubusercontent.com/38610659/39837821-0d2ee55c-53c7-11e8-8949-ab16308177f7.jpg)
![umatrix bug](https://user-images.githubusercontent.com/38610659/39837825-0e195f24-53c7-11e8-91e5-49d6a0faad71.jpg)

Also the uMatrix Popup has white borders around the refresh button.
![umatrix popup](https://user-images.githubusercontent.com/38610659/39837897-3de467d0-53c7-11e8-8249-3cd982e061c6.jpg)

Tech info:
Windows 7 64bit Pro N
Firefox Portable 59.0.3

**Comment by overdodactyl** [comment]
I believe this is a Firefox/Windows specific bug that has been fixed in v60 relating to the preference `extensions.webextensions.remote`.

See #58 and this section of the wiki:

https://github.com/overdodactyl/ShadowFox/wiki/Known-Problems#complete-styling-of-webextensions

**Comment by t2YU2m8l83** [comment]
It really was a bug. I've updated to version 60 today and all problems mentioned here are now fixed.
