### ISSUE TITLE
[Bug] Border artifacts in about:config (related to  #131)

### ISSUE THREAD

**Issue by t2YU2m8l83** [overdodactyl/ShadowFox#148]
The list in about:config has the same border-top artifact issue as the library had in bug  #131 
![unbenannt](https://user-images.githubusercontent.com/38610659/39865111-670a097a-543b-11e8-83ac-1fd39189de46.jpg)

System:
Windows 7 64bit Pro N
Firefox Portable 60.0 (bug allready occured in 59)

**Comment by t2YU2m8l83** [comment]
I'll use the single userContent/Chrome.css files but adding the snippet at the bottom of the userContent.css did work.

**Comment by overdodactyl** [comment]
Thanks! Just included it
