### ISSUE TITLE
[Bug] "Show your bookmarks"-popup has black arrows in Firefox 60

### ISSUE THREAD

**Issue by t2YU2m8l83** [overdodactyl/ShadowFox#149]
The popup window for the "Show your bookmarks" button has black arrows for folders instead of grayish/white like 59 had.

![bookmark menu](https://user-images.githubusercontent.com/38610659/39865561-d18fad30-543c-11e8-84e1-70950667d2f2.jpg)

System:
Windows 7 64bit Pro N
Firefox Portable 60

**Comment by overdodactyl** [comment]
It didn't change on macOS...is this something you could look into by chance?

**Comment by t2YU2m8l83** [comment]
The panelUI.css has the following rule
```
menu.subviewbutton > .menu-right {
	fill: currentcolor;
}
```
and because userChrome.css has
```
.menu-right {
	filter: invert(95%) !important;
}
```
the arrows turn black. I recommend to add the following code. So far, I had no problems with it.
```
menu.subviewbutton > .menu-right {
	fill: black !important
}
```

**Comment by overdodactyl** [comment]
Thanks!
