### ISSUE TITLE
panic: terminal entry not found

### ISSUE THREAD

**Issue by indeedwatson** [overdodactyl/ShadowFox#151]
I installed the script from AUR, upon running it I get:

```go
panic: terminal entry not found

goroutine 1 [running]:
main.createUI()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:177 +0x2de7
main.main()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:4 +0x20
```

Running FF nightly (62), I've tried running the script with firefox open and closed, makes no difference.

**Comment by overdodactyl** [comment]
I think this is the same problem reported in SrKomodo/shadowfox-updater/issues/7.  

In that case, the user was using `termite` terminal, which unfortunately isn't supported by the library used for the UI.

**Comment by indeedwatson** [comment]
I searched for the error in the issues and that didn't show up.

I'm using Termite, should've mentioned that, but I have never heard of a script that doesn't support a terminal. Seems to work with urxvt, thanks.

**Comment by SamHH** [comment]
I'm also experiencing this with Kitty. Alacritty works fine.

As the previous user said, this is very unusual; this is the first time I've come across an error like this in my terminal. The UI is very simple to the point that I honestly think an old fashioned setup of just passing arguments or being presented a regular text input with keyed options (latter may be better given the profile selection) would be both more compatible and easier to use.

**Comment by SrKomodo** [comment]
Alright, enough people seem to be using non-compatible terminals so i will work on adding a text-only UI that will run when the normal UI doesn't work

**Comment by SrKomodo** [comment]
now in 1.5.0 the program has a fallback text-only UI that will run if the cool UI doesnt work properly, so all of you should be able to use your fancy terminals again 🎉!

**Comment by SrKomodo** [comment]
now in 1.5.0 the program has a fallback text-only UI that will run if the cool UI doesnt work properly, so all of you should be able to use your fancy terminals again 🎉!

**Comment by overdodactyl** [comment]
Thanks @SrKomodo!
