### ISSUE TITLE
Add dark theme to bitwarden

### ISSUE THREAD

**Issue by ahmedflix25** [overdodactyl/ShadowFox#154]
* webextension name: umatrix and bitwarden
* browser version: stable
* operating system: windows

* link to the webextension in the AMO store
https://addons.mozilla.org/en-US/firefox/addon/umatrix/
https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/

**Comment by overdodactyl** [comment]
Hi @ahmedflix25, a dark theme for uMatrix is already available

**Comment by r2308145** [comment]
is bitwarden functionally above the builtin Firefox pass manager? I'm in then

**Comment by overdodactyl** [comment]
Since an account is required for Bitwarden, I'm going to add the help wanted label in hopes another user can help out with this one

**Comment by ahmedflix25** [comment]
@overdodactyl i sent an account to your email

**Comment by opes** [comment]
Bitwarden has since added their own built-in dark theme, which actually fits pretty nicely with ShadowFox.
