### ISSUE TITLE
Multi-Account Containers Pop-up issue

### ISSUE THREAD

**Issue by tkhquang** [overdodactyl/ShadowFox#155]
Is this normal? I don't recall I got this before. I've just tried to create a new profile with only Shadow Fox (no other tweaks in the userContent.css) and I see this.
![gif](https://puu.sh/AnSOh/6126031b63.gif)

I'm on Firefox 60.0.1 64-bit Windows 10 btw.

**Comment by overdodactyl** [comment]
Thanks for reporting! Should be fixed
