### ISSUE TITLE
Bookmarks bar is unstyled

### ISSUE THREAD

**Issue by NetOperatorWibby** [overdodactyl/ShadowFox#156]
Browser version: 61.0b6 (64-bit) beta
OS: macOS High Sierra

![ss 2018-05-19 at 2 03 19 am](https://user-images.githubusercontent.com/1288356/40266008-0f31f81e-5b09-11e8-9217-327de38aec06.png)

I am using the full theme.

**Comment by overdodactyl** [comment]
You'll need to activate the default dark theme Firefox provides:

Hamburger Menu > Customize > Themes > Dark

**Comment by NetOperatorWibby** [comment]
Ah, I was under the assumption this was its own standalone dark style. Half the Inspector is white though, fyi.

**Comment by overdodactyl** [comment]
>I was under the assumption this was its own standalone dark style.

The goal with this repo is just to supplement/expand the dark theme FF provides.  It saves time, prevents compatibility issues and let's users add ShadowFox onto other themes available in the AMO store.

>Half the Inspector is white though, fyi.

Same thing here.  When the inspector is open go to the settings (cog wheel) > Themes > Dark
