### ISSUE TITLE
many rss pages still with white background

### ISSUE THREAD

**Issue by metbic** [overdodactyl/ShadowFox#157]
Hello
SF is great.
But many rss pages are not affected (at least on my machine).

examples:
https://www.rt.com/rss/
https://www.reuters.com/rssFeed/worldNews

**Comment by metbic** [comment]
![fff](https://user-images.githubusercontent.com/8116828/40267222-9c27dc48-5b59-11e8-82a2-459bfefd7d26.jpg)

**Comment by metbic** [comment]
Those rss feeds that end with .rss work.
Feeds that end with .xml or others won't work.

**Comment by t2YU2m8l83** [comment]
Applying the rss page rules to a global scale and adding html#feedHandler at the start of every rule should do the trick.

```
  html#feedHandler body,
  html#feedHandler html {
    background-color: var(--in-content-page-background)!important;
    color: var(--in-content-page-color)!important
  }
  html#feedHandler h1 {
    border-color: var(--in-content-box-border-color)!important;
    color: var(--in-content-selected-text)!important
  }
  html#feedHandler #feedBody,
  html#feedHandler #feedHeader {
    background-color: var(--in-content-box-background)!important;
    border-color: var(--in-content-box-border-color)!important;
    color: var(--in-content-page-color)!important
  }
  html#feedHandler *|:link {
    color: var(--in-content-link-color)!important
  }
  html#feedHandler #subscribeButton {
    -moz-appearance: none!important;
    background: var(--in-content-page-background)!important;
    color: var(--in-content-page-color)!important;
    border: 1px solid;
    border-color: var(--in-content-box-border-color)!important;
    border-radius: 4px
  }
  html#feedHandler #subscribeButton:hover {
    background: var(--in-content-box-background)!important
  }
  html#feedHandler .enclosures {
    background: var(--in-content-page-background)!important;
    border-color: var(--in-content-box-border-color)!important
  }
```

**Comment by metbic** [comment]
Can I put these rules into one of the files in the ShadowFox_customization folder mentioned in the wiki, or will this anyhow be implemented in the future?

**Comment by t2YU2m8l83** [comment]
I think those rules will be included in the next update. If you don't want to wait on it, you can simply copy paste them at the end of the %profile%\chrome\userContent.css file.

**Comment by overdodactyl** [comment]
Thanks for reporting this @metbic, and my apologies for the delay in getting this fixed.

I appreciate the code @t2YU2m8l83!
