### ISSUE TITLE
Request for keeping userChrome.css scripts

### ISSUE THREAD

**Issue by EstherMoellman** [overdodactyl/ShadowFox#158]
Please:

Each time I update ShadowFoxCSS, it creates a new userChrome.css deleting my other CSS scripts.

Is there a way to update ShadowFoxCSS without deleting my other scripts?

Thanks in advance!

**Comment by SrKomodo** [comment]
If you want to add extra customizations, you should add them in the `userChrome_customization.css` file found in `chrome/ShadowFox_customization`, they will be automatically appended to `userChrome.css` when running the updater
Thankfully the updater makes backups so if you lost anything you can easily recover it

**Comment by EstherMoellman** [comment]
P-E-R-F-E-C-T! Thank you!

It works like a charm.

ShadowFoxCSS is so functional and beautiful... congratulations!

**Comment by seascape** [comment]
The file mentioned above does not appear to be included(?) in the 1.6.0 distribution, just to note for anyone seeking it.

**Comment by overdodactyl** [comment]
@seascape -

That file doesn't come from this repository, but rather from the updater script.  See here:

https://github.com/overdodactyl/ShadowFox/wiki/Customization

**Comment by aemonge** [comment]
I was going to create yet the same feature request...... can we put this information in the main readme ?  I think it'll be useful to many. I you want I can do the PR ;)

**Comment by overdodactyl** [comment]
readme is updated
