### ISSUE TITLE
Request 01: HTTP black padlock / HTTPS green padlock

### ISSUE THREAD

**Issue by EstherMoellman** [overdodactyl/ShadowFox#159]
Hi, I'm using FF Beta 61.0b6.

At ShadowFoxCSS padlock is always blue. Please, I need a script for the padlock:

For HTTP => Black padlock (if possible, black bold)

For HTTPS => Green padlock (if possible, green bold)

Thanks in advance!

**Comment by overdodactyl** [comment]
https://www.reddit.com/r/FirefoxCSS/comments/8kssmf/http_padlock_black_https_padlock_green/

**Comment by EstherMoellman** [comment]
Thanks @overdodactyl.

I read the Wiki link you posted (thank you!). Sorry I didn't read before. Now I understand how to customize padlock color. However, I still don't know how to have both colors, green for HTTPS, and black for HTTP.

It will be great if you can help me.

Thanks a lot!

**Comment by EstherMoellman** [comment]
@Overdodactyl ... P-E-R-F-E-C-T !!!!!!!! Everything works perfect! Thank you!

After your explanation, it was easy to change padlock color. Again, sorry I didn't read the Wiki before.

Black padlock in HTTP... also perfect!

https://old.reddit.com/r/FirefoxCSS/comments/8kssmf/http_padlock_black_https_padlock_green/
