### ISSUE TITLE
REQUEST 02: Small "flexible spaces"

### ISSUE THREAD

**Issue by EstherMoellman** [overdodactyl/ShadowFox#160]
Hi, I'm using FF Beta 61.0b6.

At ShadowFoxCSS... is there a way to change the size of the "flexible spaces" in Nav Bar?
I would like small ones.

If not possible, how can I make "separators" for the Nav Bar?

Thanks in advance!

**Comment by overdodactyl** [comment]
https://www.reddit.com/r/FirefoxCSS/comments/8kt4k1/nav_bar_small_flexible_spaces_or_separators/

[r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/) is a great place to get help with non ShadowFox/dark theme specific questions :)

**Comment by EstherMoellman** [comment]
Thanks @overdodactyl.

I read the Wiki link you posted (thank you!). Sorry I didn't read before. Now I understand how to customize padlock color. However, I still don't know how to have both colors, green for HTTPS, and black for HTTP.

It will be great if you can help me.

Thanks a lot!
