### ISSUE TITLE
Firefox Color: A Firefox Test Pilot Experiment

### ISSUE THREAD

**Issue by lhindir** [overdodactyl/ShadowFox#163]
Firefox just launched a Test Pilot experiment called [Color](https://testpilot.firefox.com/experiments/color) allowing much more customizable recoloring than stock Firefox. It's only being tested right now, but I figured I would let you know about it. It would eliminate some basic code.

**Comment by overdodactyl** [comment]
Thanks for the heads up @lhindir! I'll check out.

It would definitely help to remove some of the code base - my only initial concern would be adding on an additional step to setting up ShadowFox, but definitely worth looking into :)

**Comment by overdodactyl** [comment]
I like the idea behind Color and think it's a great way to go for some people, but since users would still have to install ShadowFox, I would rather keep everything together in one install instead of adding another step.

Thanks for letting me know about it though!
