### ISSUE TITLE
Firefox Multi-Account Containers: plus button tab side

### ISSUE THREAD

**Issue by matheusfaustino** [overdodactyl/ShadowFox#166]
Hi, first of all, thank you for your hard work.
I'm seeing a little glitch or a lack of style in the plus button from Multi Containers Addon, I think it should have more padding, I don't know.

Did you hear something about it before?

![video](https://user-images.githubusercontent.com/5246304/41467764-12377824-707e-11e8-9e8a-5e137950db58.gif)

**Comment by matheusfaustino** [comment]
Sorry, I missed the specs. 
It's Ubuntu 18.04, running Gnome 3.28.1 with Adapta-Nokto-Eta theme and firefox 61.0b13 dark theme.
I've updated the shadowfox updater - :p - to 1.5.1 and didn't change the spaces :/ 
I will try the userChrome.css after

**Comment by overdodactyl** [comment]
Merging this with #162
