### ISSUE TITLE
Dark background under the Remember the Milk logo on web app

### ISSUE THREAD

**Issue by DanielChesters** [overdodactyl/ShadowFox#167]
Hi,

I use the [Remember the Milk web app](https://www.rememberthemilk.com/app/#all) on last stable version of Firefox and I have a bug when the shadowfox theme was installed (I just try on Windows 10 with last version of shadowfox updater) : 

![rtm_ko](https://user-images.githubusercontent.com/291102/41564032-dfcd80aa-7351-11e8-9157-6ad3acdfaaf4.png)

I should look more like this : 

![rtm_ok](https://user-images.githubusercontent.com/291102/41564052-f13fe65c-7351-11e8-938f-a4062cba5092.png)

I try to inspect the web app to see which CSS rules do the bug but I found nothing for the moment.

Thank you.

**Comment by overdodactyl** [comment]
Hi @DanielChesters, thanks for reporting this! 

It should now be fixed if you want to update and give it a try.

**Comment by overdodactyl** [comment]
Never mind, that fix causes some other problems.  Reverting and re-opening until a better solution is found

**Comment by overdodactyl** [comment]
Should be resolved with the latest commit - let me know if not

**Comment by DanielChesters** [comment]
It is fine now, thank you.
