### ISSUE TITLE
Request for "UltraWide Video 21:9" extension

### ISSUE THREAD

**Issue by SlimF** [overdodactyl/ShadowFox#168]
Webextension name: UltraWide Video 21:9

Browser version: 61.0b9

Operating system: Windows 10

Link to the webextension in the AMO store:
https://addons.mozilla.org/en-US/firefox/addon/ultrawide-video-21-9/

What needs to be themed:
https://i.imgur.com/R5l7PFK.png

**Comment by overdodactyl** [comment]
Hi @SlimF, unfortunately this add-on doesn't appear to be available for macOS, which is something I actually haven't run into before (when I go to the AMO page, I get a message saying "This add-on is not available on your platform.").

Because of this, I won't be able to add a theme for it, but I would gladly accept a pull request if someone else is able to do so.

**Comment by stonecrusher** [comment]
Well, that's actually an easy one.
```
@-moz-document url-prefix("moz-extension://{f07fb9b1-1eaf-4d80-85b4-95b32557ba24}/html/popup.html") {
	html {
		background: var(--in-content-box-background) !important;
		color: var(--in-content-page-color) !important;
		border: 3px solid var(--in-content-box-border-color) !important;
}
```
@overdodactyl I'm not sure if anything else besides creating a new .css file has to be modified to make it work with the updater? I already inserted the extension ID, not the internal UUID.

**Comment by overdodactyl** [comment]
Thanks @stonecrusher, and sorry for taking so long to get back to you.

The extension ID is all you need for the updater - I usually add ones like this in their one file within the `css/userContent-files/webextension-tweaks/` directory and add an `@import` statement in `userContent_imports.css`. 

Do you want to submit a pull or should I add in that code?

**Comment by stonecrusher** [comment]
Ok thanks for the info.
It's fine when you add the code :-)

**Comment by overdodactyl** [comment]
Thanks! Just didn't want to take your code without asking incase you wanted the commit history to reflect it :)
