### ISSUE TITLE
Request for YouTube Video and Audio Downloader (WebEx) extension

### ISSUE THREAD

**Issue by SlimF** [overdodactyl/ShadowFox#169]
Webextension name: YouTube Video and Audio Downloader (WebEx)

Browser version: 61.0b9

Operating system: Windows 10

Link to the webextension in the AMO store:
https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/?src=featured

What needs to be themed:
https://imgur.com/a/CZOQcJv

**Comment by opes** [comment]
I've been looking to contribute meaningfully to ShadowFox since I've been heavily using it for some time now. I'd love to take a look at this and see what I can do.
