### ISSUE TITLE
Please theme Firefox's pop-up website notifications

### ISSUE THREAD

**Issue by LumKitty** [overdodactyl/ShadowFox#170]
browser version: 61.0 (64-bit) (beta channel)

operating system: Windows 10 v1803 (Spring Update)

explicit instructions how to get to the broken feature/webpage:

Can be done on any webpage that can create notifications (gmail, facebook etc.). In my case I'll use facebook
1) Allow pop-up notifications from Facebook
2) Create two facebook accounts and make them be friends
3) Sign into facebook with account 1 
4) From another container/browser/device sign into facebook with account 2 
5) Make a post and tag account 1 in it, e.g. post "Test: @ Jane Doe" (without the space after the @)
6) Pop up appears in the bottom left corner of your screen on Windows

how you are using ShadowFox: Shadowfox installer

![image](https://user-images.githubusercontent.com/8736448/41858510-ff257558-7891-11e8-862a-b8e3d414eecc.png)

**Comment by overdodactyl** [comment]
Hi @LumKitty - I believe notifications are controlled by your OS or the website you visit, not Firefox
itself.  

As such, I don't think this is something that can be addressed via ShadowFox.
