### ISSUE TITLE
Request for S3.Translator WebExtension

### ISSUE THREAD

**Issue by ylluminarious** [overdodactyl/ShadowFox#172]
Hi,

First of all, thanks so much for making this theme! I was recently pointed to this theme out of frustration because Firefox 61, despite improvements to the dark theme, still left out parts of the UI that ought to be darkened. This theme is really great, thanks for going to the trouble of making it!

I just have a request for the [S3.Translator](https://addons.mozilla.org/en-US/firefox/addon/s3google-translator/) extension. It is by no means an obscure extension; it currently has ~300k users according to the addons store. The only parts that need to be styled are a dropdown menu (a la uBlock Origin) and a settings page (also a la uBlock Origin).

Thanks.

**Comment by overdodactyl** [comment]
Closing in favor of #207
