### ISSUE TITLE
rss pages are white again

### ISSUE THREAD

**Issue by metbic** [overdodactyl/ShadowFox#176]
Hello

I tried 1.5.3, but after installing, the rss pages mentioned before (pages that do not end in .rss) are unaffected again, meaning that they load with a white background.

**Comment by overdodactyl** [comment]
Hi @metbic, do you have any example pages?

The ones mentioned in #157 still seem to be properly themed for me

**Comment by metbic** [comment]
hmm, I guess it's a local problem then, I can never rule out my personal incompetence.

however:
http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
http://www.lefigaro.fr/rss/figaro_flash-actu.xml
https://www.tagesspiegel.de/contentexport/feed/home
http://www.tanea.gr/rss.axd?pgid=1

all these go with a white background on my machine. I don't attach any screenshots because I applied those extra rules mentioned in #157, as a circumvention. But since the extra rules result in a slightly different color theme, I can tell that they are unaffected by SF.

**Comment by overdodactyl** [comment]
All of those appear styled on my machine.

The rules in #157 were incorporated into ShadowFox in e5ddcec.  The colors scheme should be the same, the only alteration was making the already existing style go into effect on a global scale.

**Comment by metbic** [comment]
Yes. I just tried v.1.5.5 and everything works again.



Am 19/07/18 um 17:23 schrieb Pat Johnson:

All of those appear styled on my machine.

The rules in #157<https://github.com/overdodactyl/ShadowFox/issues/157> were incorporated into ShadowFox in e5ddcec<https://github.com/overdodactyl/ShadowFox/commit/e5ddcecbc08d930dddd1c0002e30ff3d3d1bda0c>. The colors scheme should be the same, the only alteration was making the already existing style go into effect on a global scale.
