### ISSUE TITLE
Addon menus are white

### ISSUE THREAD

**Issue by 3k2** [overdodactyl/ShadowFox#178]
Hi

I have installed the theme from AUR it was working fine until I had to reset firefox settings to default from about:support menu. After that I used the updater to uninstall shadow fox theme then reapply. Some main menus are now black like they are suppose to be but for example ublock settings is white and menu you enter to block stuff etc. Noscript menu is default white.

Any ideas to fix?

**Comment by SrKomodo** [comment]
1. Make sure you are using the Firefox dark theme
2. Make sure you are using the correct profile for installing (you can go to about:profiles to see your active profile)

**Comment by 3k2** [comment]
1. 
![image](https://user-images.githubusercontent.com/11908261/42551814-e212c770-84e1-11e8-95f8-bade7c699bf2.png)

2. 

![image](https://user-images.githubusercontent.com/11908261/42551826-f11c961a-84e1-11e8-9226-591cc4335da1.png)
![image](https://user-images.githubusercontent.com/11908261/42551845-0aab8b2c-84e2-11e8-9321-1e83054a6d8d.png)

seems to be correct..

**Comment by SrKomodo** [comment]
Is the "Auto-Generate UUIDs" option checked?

**Comment by n-o-o-b** [comment]
Thanks, that fixed it! Greasemonkey looks better now, too.

**Comment by Caspy7** [comment]
> Is the "Auto-Generate UUIDs" option checked?

Is there a reason this is not checked by default?

**Comment by SrKomodo** [comment]
The "Auto-generate UUID's" option removes any customizations you have in `internal_UUIDs.txt`, so it's safer to have it opt-in. Some people choose to manually edit the file so that only certain extensions get styled.

**Comment by 3k2** [comment]
> Hmm. Can you go to the root folder (click "open directory"on about:profiles) and tell me what's in the chrome folder?

Sorry for late reply but I fixed my issue by deleting folder `/home/steve/.mozilla/firefox/hpcy9bdp.default-1531243544800/chrome/` after that I reapplied the shadowfox updater and it worked just fine! must have been some issue from reseting the profile to default then it might have left some ghost things behind?

**Comment by overdodactyl** [comment]
Looks like the issues have been resolved, feel free to re-open if I'm missing something.

Thanks for the help @SrKomodo!
