### ISSUE TITLE
Firefox Portable

### ISSUE THREAD

**Issue by anubis-genix** [overdodactyl/ShadowFox#179]
1.
Are there any plans to make Shadowfox Updater compatible with Firefox Portable? 
Maybe by entering the profile path manually?
Download: https://portableapps.com/apps/internet/firefox_portable
I tried t2YU2m8l83's solution from https://github.com/overdodactyl/ShadowFox/issues/127 but it didn't work on my side. Had to copy the files myself into the chrome folder.

2.
Creating an internal_UUIDs.txt file in the folder Shadowfox_customization and manually importing the extensionUUID and internalUUID for certain addons like uBlock and CookieAutoDelete also won't work. Is there something I'm missing or misinterpreting?

**Comment by overdodactyl** [comment]
>Are there any plans to make Shadowfox Updater compatible with Firefox Portable? Maybe by entering the profile path manually?

@SrKomodo would best be able to answer this question, but I am surprised the solution in #127 didn't work for you.  Are you sure the your files are located in the correct location? 

>Creating an internal_UUIDs.txt file in the folder Shadowfox_customization and manually importing the extensionUUID and internalUUID for certain addons like uBlock and CookieAutoDelete also won't work. Is there something I'm missing or misinterpreting?

The UUIDs need to be placed in the actual css.  When using the updater, the UUIDs are transferred from `internal_UUIDs.txt` into their respective locations within `userContent.css`, thus without the updater, you would have to do this part manually.  `internal_UUIDs.txt` is simply a way to store your UUIDs in one convenient location and not lose them between updates.

As an example, for uBlock Origin, the UUID would have to be placed in two locations:

https://github.com/overdodactyl/ShadowFox/blob/c0b767cbf13dcb77e0ea6ff0b501a25888013008/userContent.css#L2216-L2220

https://github.com/overdodactyl/ShadowFox/blob/c0b767cbf13dcb77e0ea6ff0b501a25888013008/userContent.css#L1608-L1612

**Comment by SrKomodo** [comment]
The solution in #127 should work, if you dont have a profiles.ini file just create one and have it point to where the chrome folder should be.

As i said before, if for example your chrome folder is in `Firefox/Profiles/foo/` then `profiles.ini` should look like this:
```
[Foo]
Path=Profiles/foo
IsRelative=1
```
and the file should be placed on `Firefox/`

**Comment by anubis-genix** [comment]
Now I got it to work. Looks like I've put the profiles.ini file in the wrong directory to begin with. Thanks for the help!
