### ISSUE TITLE
New tab empty page now has a white background

### ISSUE THREAD

**Issue by SW1FT** [overdodactyl/ShadowFox#186]
Browser: Firefox 63.0a1
Operating system: Windows 10
Updating method: ShadowFox Updater
Note: The weird thing about this is that the new tab page is not white if you open a new window but as soon as you open another new tab it shows a white page now.
Screenshot:
![newtabwhite](https://user-images.githubusercontent.com/6627739/45026821-62ad1400-b037-11e8-99e5-7f5acc0da0fa.png)

EDIT: As I said in the title, I set my new tab page to be fully empty.

**Comment by overdodactyl** [comment]
Thanks @SW1FT.

I think this was a result of the fix implemented for #182.  The latest commit should resolve things, feel free to re-open if not
