### ISSUE TITLE
View Certificates dialog tabs slightly mis-styled

### ISSUE THREAD

**Issue by Cryosaur** [overdodactyl/ShadowFox#188]
The active tab label in the Options > Privacy & Security > View Certificates... dialog is not very readable; the text color does not change from its inactive state.

Firefox 62.0 (64bit)
![certificates](https://user-images.githubusercontent.com/1138967/45534243-80614280-b7c8-11e8-9d8e-2a013e4d3991.jpg)

**Comment by overdodactyl** [comment]
Thanks for letting me know @Cryosaur! 

Should be fixed in the latest version
