### ISSUE TITLE
Remove 'node_modules' from repo, add 'package.json'

### ISSUE THREAD

**Issue by fhemberger** [overdodactyl/ShadowFox#189]
Although you added 'node_modules' to `.gitignore`, the whole directory is still part of the GitHub repo. You can remove files from your repository history using either the [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/):

```
git clone --mirror git@github.com:overdodactyl/ShadowFox.git
java -jar bfg.jar --delete-folders node_modules ShadowFox.git
```

Also the main `package.json` is missing in the project's root.

This would make contributing easier.

**Comment by overdodactyl** [comment]
Hi @fhemberger, thanks for opening the issue.

I think I've properly removed the node_modules directory and created the `package.json` file

**Comment by fhemberger** [comment]
Great, thank you!
