### ISSUE TITLE
Support for Tor-Browser

### ISSUE THREAD

**Issue by qazip** [overdodactyl/ShadowFox#192]
Hey,

I was wondering if anyone has managed to make the installer work for the Tor-Browser. I use the Tor-Browser without connecting to the Tor network since it has better privacy defaults.

If it's not currently possible, due to the folder structure, please consider this a feature request.

**Comment by SrKomodo** [comment]
try going to `about:profiles`, go to the profile path, and then go back a few folders until you see `profiles.ini`, once you see it, copy the updater executable to wherever `profiles.ini` is located and try running it there.

**Comment by qazip** [comment]
Oh, it worked. Thank you @SrKomodo !!

**Comment by ylluminarious** [comment]
Can confirm; this indeed works. Awesome!
