### ISSUE TITLE
ShadowFox breaks TreeStyleTab

### ISSUE THREAD

**Issue by qazip** [overdodactyl/ShadowFox#193]
Please see [this](http://i.imgur.com/pjsQOid.png) screenshot and this [issue](https://github.com/piroor/treestyletab/issues/2040) in TST's repository.

**Comment by overdodactyl** [comment]
Thanks for reporting the problem - should be fixed in the latest version.

If there are any further problems, feel free to re-open or open a new issue

**Comment by qazip** [comment]
How soon can I use the auto-updater?

**Comment by overdodactyl** [comment]
You can do so now. The updater pulls directly from the repo, so as soon as a change is made on GitHub, it will be available via the updater

**Comment by qazip** [comment]
I confirm it's fixed!
