### ISSUE TITLE
uBlock Element Picker no transparency

### ISSUE THREAD

**Issue by Cryosaur** [overdodactyl/ShadowFox#196]
Firefox 62.0 (64bit)
uBlock Origin 1.17.0
ShadowFox 1.7.10.0
Windows 10 Pro

uBlock Origin's element picker mode under ShadowFox is not styled as partially transparent, so it is impossible to use.

**Comment by overdodactyl** [comment]
Thanks for letting me know @Cryosaur - should be fixed if you want to update

**Comment by overdodactyl** [comment]
Thanks for the link @gwarser
