### ISSUE TITLE
Customization of dev panel

### ISSUE THREAD

**Issue by Crandel** [overdodactyl/ShadowFox#199]
Hello again. I`m successfully replace all blue colors to green except tabs in dev panel. Is it possible to replace blue accent to green in this tabs? 

![](https://habrastorage.org/webt/2i/qu/el/2iquela7wgmthsz5ubl1enlflq4.png)   

Also I found a strange white line in this panel. When I rename **userChrome.css** and **userContent.css** this line is disappearing.
This line block my console tab, I`m not able to write javascript code inside console.

I use latest version of shadowfox-updater and this is my **ShadowFox** [settings](https://github.com/Crandel/home/tree/master/.mozilla/firefox/chrome/ShadowFox_customization)

**Comment by overdodactyl** [comment]
Hi @Crandel,

The tab line is controlled by `--tab-line-selected-color`, which now defaults to `--accent-2`.

It looks like the following lines from your `userChrome_customization.css` are causing the problem:

https://github.com/Crandel/home/blob/5e9f75b8b2f0b68081f7ccd4b9c5b71bb06380e1/.mozilla/firefox/chrome/ShadowFox_customization/userChrome_customization.css#L31-L34

**Comment by Crandel** [comment]
I\`m not able to find `--tab-line-selected-color` variable in my **userChrome.css**. How to enable it?
About white line. I fix mistake and changed color from white to dark, but text also became dark so I\`m able to see the text only if I select it. Is it possible to override color exactly for console textarea? 
Because my modifications let me change textarea colors in all websites I use and I want to keep them.

**Comment by overdodactyl** [comment]
`--tab-line-selecected-color` was added in the latest commit (5fe368c), so you might have to update if you haven't done so already.  It should default to `--green-80` for you now. 

You can target the textarea for the console using `textarea.jsterm-input-node`.  That being said, removing those lines from `userChrome_customization.css` shouldn't have any effect on your customizations on websites - generally speaking, `userContent` alters webpages (`about:` pages, regular web addresses etc.), while `userChrome` alters browser components

**Comment by Crandel** [comment]
Thank you very much for a really quick fix. Everything works great right now.

**Comment by overdodactyl** [comment]
No problem, glad it works!

I noticed some other areas where ShadowFox doesn't switch the default blue, so I've opened up #200.  Feel free to add comments there for any elements you notice/would like to be able to change.
