### ISSUE TITLE
How can one check the version of the installed ShadowFox version?

### ISSUE THREAD

**Issue by fad1** [overdodactyl/ShadowFox#201]
(Tried asking on slack and reddit but very few people are present)

Thanks

**Comment by fad1** [comment]
thanks

**Comment by overdodactyl** [comment]
Hi @fad1 - sorry I didn't yet see your slack message.

Up until now, I haven't been keeping track of versioning.  From here forth, you'll be able to look at the very top of either `userContent.css` or `userChrome.css`.  I made a rather arbitrary decision to begin now with 1.5.0.  

Hopefully this solves things!

If you'd like to see it in a different place as well, feel free to let me know :)
