### ISSUE TITLE
shadowfox updater overwrites user.js in firefox profile folder

### ISSUE THREAD

**Issue by jorjio** [overdodactyl/ShadowFox#202]
Hi!
in the shadowfox updater the option of setting firefox dark theme is overwriting the user.js file.
it would be nice if those user.js lines could be appended to the file instead.

thanks!
![image](https://user-images.githubusercontent.com/5610394/46589131-4e17cd80-ca74-11e8-84a5-c3e6e108e499.png)

**Comment by SrKomodo** [comment]
the updater makes backups, so you can recover your old user.js, and v1.7.11 should have this fixed. It took me some time to upload it because travis CI isn't behaving so i had to upload the binaries manually but everything should be working fine.

**Comment by overdodactyl** [comment]
Thanks for the quick fix. Website's updated with v1.7.11 as well.

I'm noticing a slightly odd behavior when using that option:

Steps to reproduce:

1) Create a user.js file with an arbitrary first line entry.

2) Run the updater with "Set Firefox dark theme" checked

Result: A backup is created and the lines are appended to user.js

3) Run the updater with "Set Firefox dark theme" checked a second time

Result: `user.js` is backed up, but a version of `user.js` is not kept

**Comment by SrKomodo** [comment]
Again, just me being stupid with the order in which things are done, v1.7.12 should fix this

**Comment by overdodactyl** [comment]
Thanks! Website's updated
