### ISSUE TITLE
Get Add-ons text and other parts not colored correctly.

### ISSUE THREAD

**Issue by thakyZ** [overdodactyl/ShadowFox#208]
Browser Version: 63.0 (64-bit)
OS: Windows 7
Reproduce:
- Go to add-ons page and click get "Add-ons"
- Notice the text being weird.

Screenshots:
![image](https://user-images.githubusercontent.com/950594/47452129-4ba8b980-d77e-11e8-854f-b716c56b4b4d.png)
![image](https://user-images.githubusercontent.com/950594/47452143-4fd4d700-d77e-11e8-8201-b0036eab864e.png)

**Comment by overdodactyl** [comment]
Thanks for opening the issue...should be fixed!
