### ISSUE TITLE
uMatrix icons breaking soon

### ISSUE THREAD

**Issue by Zlewness** [overdodactyl/ShadowFox#210]
This is a bug in a future version of uMatrix, 1.3.15. They've moved onto fontawesome icons for the toolbar, which aren't styled using this css.

To recreate, install the 1.3.15 rc1 using https://github.com/gorhill/uMatrix/releases and view the 3 icons on the top right in the popup.

**Comment by overdodactyl** [comment]
Thanks for the heads up and early report @Zlewness.

I've added a quick fix that should work for the icons in the popup toolbar and the logger.

I'll keep this open for now until I make sure I've got everything and to remind me to remove the old styling once this version of uMatrix hits AMO.

If you find anything else, please feel free to let me know :)

**Comment by overdodactyl** [comment]
Looks like we should be good hear - feel free to open a new issue/reopen if I've missed something.

Thanks again!
