### ISSUE TITLE
Extension Theming Broken

### ISSUE THREAD

**Issue by Devo7v** [overdodactyl/ShadowFox#211]
@overdodactyl  It looks like you broke the part of the updater that replaces the extension UUID's.  In your latest update you hardcoded the unique UUID's into the CSS so now the updater cannot find the generic UUID's to replace.  Please revert commit [cdbb6b4](https://github.com/overdodactyl/ShadowFox/commit/cdbb6b4af84715a5ccd6f760ceb43e5557f2f494).

**Comment by overdodactyl** [comment]
Hi @Devo7v, thanks for the report.  

Looks like my gulp task to remove UUIDs didn't get run before pushing.  

Should be fixed now
