### ISSUE TITLE
[extension-blacklist]FoxAuth

### ISSUE THREAD

**Issue by Riajyuu** [overdodactyl/ShadowFox#212]
Hi
I'm organization owner of https://github.com/FoxAuth/

As we are trying to following Photon Design which doesn't provide a dark theme yet, so we are tracking relevant support ticket to see what we can do.

Please don't create a dark theme for FoxAuth **for now** event if some one asks to.

I will see what will happen at that time and perhaps re-decide.

**Comment by overdodactyl** [comment]
No problem.

See [here](https://github.com/overdodactyl/ShadowFox/wiki/Webextensions#webextension-blacklist)
