### ISSUE TITLE
FF Nightly latest update: Blue

### ISSUE THREAD

**Issue by EstherMoellman** [overdodactyl/ShadowFox#215]
Hi,

At FF Nightly latest update, the TabBar and MenuBar are blue.

Here is the image: https://imgur.com/a/NFm4H5d

The image was took at FF Nightly clean install with dark theme + ShadowFox clean install.

Thanks

**Comment by overdodactyl** [comment]
I can't reproduce, and I don't think there is any code in ShadowFox that could be doing this - ShadowFox doesn't style the TabBar or MenuBar, nor have that shade of blue as a preset value.  

Can you try with a fresh profile and make sure there are no Firefox Color themes or system themes effecting this?

**Comment by EstherMoellman** [comment]
> 
> 
> I can't reproduce, and I don't think there is any code in ShadowFox that could be doing this - ShadowFox doesn't style the TabBar or MenuBar, nor have that shade of blue as a preset value.
> 
> Can you try with a fresh profile and make sure there are no Firefox Color themes or system themes effecting this?

PROBLEM:
I found the culprit: Windows!
I don't know if it is a Windows' bug or just a new Windows' rule, but Windows' system color settings now seem to be applied to everything, including non-Windows apps, programs etc.
At Windows colors I had "Title bars" as blue, so yesterday my FF' TabBar & MenuBar went to blue... awful! 

SOLUTION:
Unchecking "Title bars" solved the blue, and stopped interfering with non-Windows software colors.
I believe this info might be interesting for ShadowFox' users, in case of dealing with same issue. 

I apologize for thinking that the problem was ShadowFox (I couldn't imagine that was Windows).
I am closing the issue.

Thank you!

**Comment by overdodactyl** [comment]
Thanks for the update and letting me know the solution you found!

And no worries :)
