### ISSUE TITLE
Toolbar gets smaller

### ISSUE THREAD

**Issue by zCri** [overdodactyl/ShadowFox#216]
Firefox 63.0.1
OS: Windows 10

Basically in this version, when you apply shadowfox the toolbar (or whatever it's called) gets smaller.
I haven't looked at the code yet so i haven't seen any bugs.

Anyways, the screenshot of my current toolbar is this:
https://gyazo.com/97684062db89e928dee59af81914d1a3
while it clearly should be this:
https://gyazo.com/36f3c5f45b1025c36c615205f08aad5c]

**Comment by overdodactyl** [comment]
Hi there @zCri - 

Your second link is broken, but I assume this is just the density setting of Firefox. 

See #213.

Feel free to re-open if not, but there's no css styling to shrink the toolbar in ShadowFox
