### ISSUE TITLE
PDF viewer's toolbar not themed

### ISSUE THREAD

**Issue by advicepyro** [overdodactyl/ShadowFox#218]
OS: macOS 10.14.1
Browser version: Beta 64.0 b7 
Using complete theme via shadowfox-updater

The PDF viewer's toolbar isn't themed properly, with a white toolbar background and a transparent popup menu.

![screen shot 2018-11-07 at 4 05 18 pm](https://user-images.githubusercontent.com/6377466/48161089-be01b980-e2a7-11e8-9a67-1b0efd84b6e4.png)

**Comment by overdodactyl** [comment]
Thanks for the bug report @advicepyro!

Should be fixed :)

**Comment by advicepyro** [comment]
What a speedy fix! Many thanks 👍
