### ISSUE TITLE
Certificate Viewer dialog not themed

### ISSUE THREAD

**Issue by advicepyro** [overdodactyl/ShadowFox#220]
OS: macOS 10.14.1
Browser version: Beta 64.0 b7
Using complete theme via shadowfox-updater

Probably related to #153 - this dialog isn't themed, per this screenshot:

<img width="704" alt="screen shot 2018-11-15 at 10 42 07 am" src="https://user-images.githubusercontent.com/6377466/48563960-77254c80-e8c3-11e8-84cd-74f598642a66.png">

**Comment by overdodactyl** [comment]
Thanks for the report @advicepyro!

I've added some initial styling, but I think this whole dialogue (along with page info) could use some improvements, so I'll keep this open until that is complete.

 
<img width="704" alt="screen shot 2018-11-15 at 9 23 53 am" src="https://user-images.githubusercontent.com/33071129/48566714-b5693e80-e8b8-11e8-943f-941e7ebf33b0.png">

**Comment by overdodactyl** [comment]
Feel free to open a new issue if there are any further suggestions or problems.
