### ISSUE TITLE
about:webrtc is hard to read as it is not properly themed

### ISSUE THREAD

**Issue by nirojanv** [overdodactyl/ShadowFox#221]
Browser version: 64b11
OS: macOS 10.14.1

`about:webrtc` page is hard to read as it doesn't seem to be properly themed like some other about pages. I think colour's similar to that of `about:support` page should make it more readable.

For `about:webrtc` stats page to be populated, make sure you open the test URL first.

Test URL: https://meet.jit.si/shadowfox

![image](https://user-images.githubusercontent.com/22147724/48905862-9a6b7100-ee5a-11e8-86a9-1d4b6122dfad.png)

**Comment by overdodactyl** [comment]
Thanks for the bug report @nirojanv! Really appreciate the test URL as well.

I've added some styling if you want to give it a look and let me know what you think :)

**Comment by overdodactyl** [comment]
Feel free to re-open if their are any issues.suggestions for it.
