### ISSUE TITLE
Promethease report view unreadeable

### ISSUE THREAD

**Issue by labo-css** [overdodactyl/ShadowFox#222]
Hi, on last version of firefox this extension is killing the forms present on a promethease report, here is an example : https://files.snpedia.com/reports/promethease_data/genome_Mike_Spear_pooled_ui2.html

The form on the right should be white and readable. It's kinda annoying to have to uninstall Shadowfox each time i have to use that website ^^'

**Comment by labo-css** [comment]
This workaround works for me, thanks :)

**Comment by labo-css** [comment]
Looks like i can't download on mega.nz with that module on

**Comment by overdodactyl** [comment]
Thanks for letting me know! Interestingly, the same code works if applied via Violenmonkey, so I'm not positive what's going on with the webextension version.  

I'll hopefully find a fix and let you know.

**Comment by overdodactyl** [comment]
Hi @labo-css, sorry for the delay - I've just uploaded v1.1 to AMO, which I believe solves the problem

**Comment by overdodactyl** [comment]
I'm going to go ahead and close this since the Promethease issue was fixed, but feel free to open new issues with any further problems
