### ISSUE TITLE
Extra flash after page is done loading

### ISSUE THREAD

**Issue by ReekyMarko** [overdodactyl/ShadowFox#224]
Shadowfox seems to introduce an extra flash after a page is done loading. This doesn't happen on all sites, but so far I've found that it happens on reddit, facebook and vimeo. It does not happen on "lightweight" sites such as google and duckduckgo.

This issue is kind of hard to explain so here is a [video I recorded about it](https://vimeo.com/304871245)

Additional information:
```
OS: Arch Linux
Firefox version: Nightly 65.0a1 (2018-12-06) (64-bit)
Shadowfox version: 1.6.0
```

EDIT: Just tested that this happens also on stable firefox (63.03)

**Comment by ReekyMarko** [comment]
Okay I found the culprit, started disabling addons one-by-one and it seems that the problem goes away if I disable "Vim Vixen".

**Comment by overdodactyl** [comment]
Hi @ReekyMarko - thanks for the report and tracking it down to Vim Vixen.  It should be fixed in the latest version, but feel free to re-open and let me know if it's not.

**Comment by ReekyMarko** [comment]
Wow that was fast :clap:
