### ISSUE TITLE
Having issues styling addon's sidebar TreeStyleTabs

### ISSUE THREAD

**Issue by azizLIGHT** [overdodactyl/ShadowFox#228]
I am trying to restore styling I had for a sidebar for an extension called TreestyleTabs but having difficulty figuring it out.

This is what my sidebar looked before:
![image](https://user-images.githubusercontent.com/8013867/50122669-a533de80-022b-11e9-96b0-5c7f6b0661ee.png)

And this is what my sidebar looks like now:
![image](https://user-images.githubusercontent.com/8013867/50122189-613fda00-0229-11e9-9e37-f0a8d2b12290.png)

I'm trying to restore the sidebar's black background, tab borders, and some text styling so that there is more contrast and the indentation between parent and child tabs, and tab groups, is more visible. Right now it is very hard to see things because of how similarly they are styled.

I tried using [the rules given in TST's wiki to style the tabs](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-styling-of-pending-unloaded-tabs-1363) from within TST preferences but I think shadowfox userChrome.css and userContent.css were overriding them.

```
/* Change styling of pending (unloaded) tabs */
.tab.discarded {
  opacity: 0.9;
}

.tab.discarded .label {
  color: darkgray;
}
```

I also found [another example with the contrast I want:](https://www.reddit.com/r/FirefoxCSS/comments/7e8x3y/tree_style_tab_flat_dark_theme_vertical)
![image](https://user-images.githubusercontent.com/8013867/50122229-83395c80-0229-11e9-98c5-10ebe49bd341.png)

 I tried using some of the rules provided there inside TST preferences but, again, shadowfox seems to be overriding them. 

I'm not entirely sure what the difference is and where to edit, after trying to check the diff between old and new userChrome.css and userContent.css so I am lost. I have linked the files in gist below:

Details:
* Firefox 64
* Ubuntu 14.04
* [Treestyletabs Addon](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) 
* [Current Full userChrome.css and userContent.css](https://gist.github.com/azizLIGHT/d2fd3c348a9baaf45e6a64165a1d7bb8) (my modifications are at bottom of each file, if any) 
* [Old userChrome.css and userContent.css with correct contrast](https://gist.github.com/azizLIGHT/f058928a1f0d02ac1e1ec7f1775e5440) (my modifications are at bottom of each file, if any) 

I could just restore the old files and forget about it but I would be missing out on the new updated styling Shadowfox gives and any bugfixes etc. Is it possible to restore my old styling?

**Comment by overdodactyl** [comment]
ShadowFox has styling for TST included in the repo:

https://github.com/overdodactyl/ShadowFox/blob/master/css/userContent-files/webextension-tweaks/tree_style_tab.css

When using the installer, if you check the "auto generate UUIDs" box, styling for all available extensions is activated.

If you want to exclude the styling for an extension, you can delete the entry from the file `internal_UUIDs.txt` and re-run the updater (without the "auto generate UUIDs" box clicked):

https://github.com/overdodactyl/ShadowFox/wiki/Customization

If you want to keep most of the styling, but override some of the options, you can add custom styling to the `userContent_customization.css` file and re-run the updater.

For example, 

```css
@-moz-document url-prefix("moz-extension://YOUR_TST_INTERNAL_UUID/") {
  #background,
  #background::after,
  #tabbar {
    background: black !important
  }
}
```

Hope this helps!
