### ISSUE TITLE
Add support for Library and About Firefox

### ISSUE THREAD

**Issue by Sporif** [overdodactyl/ShadowFox#23]
To inspect them: 

Library - chrome://browser/content/places/places.xul

About Firefox  - chrome://browser/content/aboutDialog.xul

This is what I have for the latter in userChrome.css:

```
@-moz-document url(chrome://browser/content/aboutDialog.xul) {
    #clientBox {
        color: var(--primary-light-color) !important;
        background-color: var(--primary-dark-color) !important;
    }

    #bottomBox {
        background: var(--primary-dark-color) !important;
    }
}
```

The @-moz-document rule isn't really needed though.

**Comment by overdodactyl** [comment]
Thanks @Sporif!

I'll look into these :)

I appreciate the links for how to inspect them

**Comment by overdodactyl** [comment]
@Sporif,

I just checked out your changes to the About Firefox dialog...looks great!

**Comment by xAphex** [comment]
Code for Library:

@-moz-document url(chrome://browser/content/places/places.xul) {

	window, page, dialog, wizard, prefwindow {
		background-color: var(--primary-dark-color) !important;
	}

	.plain {
		background-color: var(--primary-dark-color) !important;
	}

	#placesToolbar {
		background-color: var(--primary-dark-color) !important;
	}

	#downloadsRichListBox {
		background-color: var(--primary-dark-color) !important;
	}

	/* this treechildren is supposed to be highlight for text, but it doesn't work because i don't know how to make the css load it.
	it's supposed to load from "chrome://global/skin/tree.css" ((line 399)) */
	treechildren {
		--treechildren-selectedFocusCurrentImage: linear-gradient(var(--mid-way-color), var(--mid-way-color)); /* ((line 419)) */
		--treechildren-hoverImage: linear-gradient(var(--dark-accent), var(--dark-accent)); /* ((line 422)) */
		--treechildren-hoverSelectedImage: linear-gradient(var(--mid-way-color), var(--mid-way-color)); /* ((line 428)) */
	}

}

**Comment by overdodactyl** [comment]
Thanks for this @xAphex!

What does this look like on Windows for you?  On a mac, it seems to only style the background of the entry area.

I had some similar experiences on the sidebar where most solutions that worked on Windows didn't work on a mac :/

![library](https://user-images.githubusercontent.com/33071129/34059301-54951a64-e1d6-11e7-8021-bfd251101801.png)

**Comment by xAphex** [comment]
@overdodactyl https://image.prntscr.com/image/UayCUsTYRcmy8b0puo7F8A.png

**Comment by overdodactyl** [comment]
Hmm so it is a mac specific issue :/ Thanks! I'll tinker with it a bit tonight :)

**Comment by Sporif** [comment]
No idea why setting the variables don't work for treechildren, but directly styling them seems to work. 

```
treechildren:not(.autocomplete-treebody)::-moz-tree-row(selected, current, focus) {
    background: var(--mid-way-color) !important;
    border: none !important;
}
        
treechildren:not(.autocomplete-treebody)::-moz-tree-row(hover) {
    background: var(--dark-accent) !important;
}
        
treechildren:not(.autocomplete-treebody)::-moz-tree-row(hover, selected) {
    background: var(--mid-way-color) !important;
}
```

**Comment by overdodactyl** [comment]
Thanks @Sporif!  That did work for the hover/selected.

Haven't tried it yet, but I assume I can use `::-moz-tree-row(odd)` and `::-moz-tree-row(even)` to style the backgrounds of the other items

**Comment by overdodactyl** [comment]
Support for the About Firefox Dialog has been added.

Additionally, my first pass at the Library has been completed.  Any feedback/suggestions for improvements are always welcome.  (Only tested on macOS)

**Comment by xAphex** [comment]
thanks for the updated!

2 issues i have found on windows 10 on firefox nightly latest version 64 bit

1. Downloads folder isn't fully dark themed | [Image](https://image.prntscr.com/image/ezlTbzz-QciB-BazXO_T5Q.png)

2. Highlight hover color is still white | [Image](https://image.prntscr.com/image/iCZRQKYhSQCPM1A1wMDdmw.png)

**Comment by overdodactyl** [comment]
Thanks @xAphex!

Downloads section should be good now.  Hover color is a little odd, I'm not see that on my mac

**Comment by overdodactyl** [comment]
If anyone has any problems or suggestions for the Library, feel free to open up a new issue/submit a pull request.
