### ISSUE TITLE
FF Portable Install not working when Full version is on PC

### ISSUE THREAD

**Issue by RoxKilly** [overdodactyl/ShadowFox#230]
I followed the instructions in [issue 179](https://github.com/overdodactyl/ShadowFox/issues/179) to get the installer to work on Firefox Portable.  However I also have the full version of Firefox installed and the ShadowFox installer would only see the full version's profiles.

So I couldn't get things to work by creating a `profiles.ini` file in the Firefox Portable location.  To get things to work, I modified the `profiles.ini` of the full version to add the Portable profile as a fully qualified path.  The 2nd profile below is what I added
```
[Profile0]
Name=default
IsRelative=1
Path=Profiles/56ess5d5.default
Default=1

[Profile1]
Name=portable
Path=C:\Users\MyUserName\PortableApps\FirefoxPortable\Data\profile
IsRelative=0
```

Suggest the installer concatenates and lists all the profiles it finds even if they are from different Firefox locations.

Also suggest that you add Firefox Portable instructions to the README.

Thank you for your great contribution.

**Comment by overdodactyl** [comment]
Thanks for reporting and the idea @RoxKilly ! Would you mind submitting the issue to the updater's repo?

https://github.com/SrKomodo/shadowfox-updater/issues

Pinging @SrKomodo just in case.

My apologies for the delayed response.

**Comment by SrKomodo** [comment]
Sorry for the late reply, the latest version now concatenates all profile.ini paths instead of stopping on the first one

**Comment by overdodactyl** [comment]
Thanks for the update!
