### ISSUE TITLE
uBlock Origin logger

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#236]
The new version of uBlock Origin got a reworked logger UI which shows white backgrounds or bad contrast:
![2019-01-25 01_18_54-ublock protokoll der netzwerkanfragen](https://user-images.githubusercontent.com/1388389/51717101-cf08ce00-203f-11e9-915f-ff51a6ce357f.png)
![2019-01-25 01_19_20-ublock protokoll der netzwerkanfragen](https://user-images.githubusercontent.com/1388389/51717102-cfa16480-203f-11e9-81ca-a1bcee739398.png)
![2019-01-25 01_19_36-ublock protokoll der netzwerkanfragen](https://user-images.githubusercontent.com/1388389/51717103-cfa16480-203f-11e9-8429-b35b268e21c8.png)
![2019-01-25 01_20_09-ublock protokoll der netzwerkanfragen](https://user-images.githubusercontent.com/1388389/51717104-cfa16480-203f-11e9-93a3-e0e3d7eeea74.png)

**Comment by overdodactyl** [comment]
Thanks for the report - I'll try and get a fix out later tonight

**Comment by overdodactyl** [comment]
I've made some changes to the logger if you want to try updating.  I don't use it that frequently, so feedback is always welcome

**Comment by Kezxo** [comment]
I updated just now and the log became all weird if you use the colorblind settings in ublock origin, it's red and blue or possibly purple now.

Even if you fix the incorrect colors, could you also please make it a bit brighter like it is in the main ublock popup?
![2019-02-10_20-43-38](https://user-images.githubusercontent.com/4523551/52538605-edc3d000-2d74-11e9-894e-ca9f2944ba3c.png)
Use all these colors please, especially the background. This is perfect in my opinion.

**Comment by stonecrusher** [comment]
I've made [some fixes](https://github.com/overdodactyl/ShadowFox/compare/master...stonecrusher:patch-1?expand=1). Please @overdodactyl review and / or I can make a PR.

- Note the unrelated typo (?) fix in `color_variables.css`
- What should the url-prefix("about:blank ") part do? Can't find a difference when commenting out. And I'm not sure if nested @-moz-document is a valid thing.
- Brightened general font color
- Fixed dropdowns
- I guess everything containing `#netInspector` `#domInspector` and `#netFilteringDialog` can be moved to `url-prefix("moz-extension://blablabla/logger-ui") ` section (didn't do that yet)

@Kezxo 
Why do you use colorblind mode at all?
ShadowFox is made to replace the given colorscheme completely. Of course it is possible to also include rules for colorblind mode but I don't want to invest the time for no reason and only one person.

**Comment by overdodactyl** [comment]
Thanks @stonecrusher!

I opened up PR #245 with your commits.

> What should the url-prefix("about:blank ") part do?

It's supposed to style the cosmetic filter popup 

>Can't find a difference when commenting out. And I'm not sure if nested @-moz-document is a valid thing.

You are correct, it appears it got nested somehow and it doesn't work, it should be it's own rule outside the brackets of the previous.

>Brightened general font color... Fixed dropdowns

Looks good!

> I guess everything containing `#netInspector` `#domInspector` and `#netFilteringDialog` can be moved to `url-prefix("moz-extension://blablabla/logger-ui") ` section (didn't do that yet)

Agreed.

**Comment by overdodactyl** [comment]
Looks like the way I made the PR doesn't give me any write access...can you either move the `about:blank` into it's own rule or submit a new PR with the changes that I can then edit?

**Comment by stonecrusher** [comment]
Added `about:blank` section again
Reordered by element
Added you as collaborator in my fork (check you're on branch `patch-1`)

**Comment by overdodactyl** [comment]
Thanks!

**Comment by Kezxo** [comment]
> Why do you use colorblind mode at all?

Well, I'm colorblind. 

> ShadowFox is made to replace the given colorscheme completely. Of course it is possible to also include rules for colorblind mode but I don't want to invest the time for no good reason and only one person.

That should not be necessary since it worked great before? Shadowfox worked great with the old logger, it just used the colors that the extension used (besides the bright ones). Just look at the screenshot I posted, that part of ublock works great with shadowfox.

**Comment by stonecrusher** [comment]
What benefits do you have by turning colorblind mode on if ShadowFox replaces everything anyway?
However, at the moment SF does not support colorblind mode and it would be better to turn it off and then tell what's wrong.
By the way maybe I'll make a rewrite of the whole uBO dark theme [based on the original rules](https://github.com/stonecrusher/uBO-dark/blob/master/uBO-original-base-merged.css) - colorblind mode not included, shouldn't be necessary. uBO itself relies quite a lot on colors so depending on the type of colorblindness it cannot be fixed. Should take into account the most common red-green-blindness though.

**Comment by Kezxo** [comment]
Shadowfox doesn't replace everything, just look at [the screenshot](https://github.com/overdodactyl/ShadowFox/issues/236#issuecomment-462165618). Even though colorblind mode isn't supported that popup menu is still way more usable to me in colorblind mode. 
The main problem I have right now is that it seems that the colorblind settings are not getting applied when using the logger with shadowfox, this was not a problem before ublock updated it's logger. Blocked objects in the log should be blue with colorblind mode on, with shadowfox they are red. This should be easy to reproduce.
Forget what I said about the brighter thing, that's barely an issue. I just want the original block and allow colors 
Examples of inconsistent colors in the logger with shadowfox:
This is wrong, should be blue:
![2019-02-11_21-18-41](https://user-images.githubusercontent.com/4523551/52590886-c6d3cf80-2e42-11e9-98f6-d0f7c761fca2.png)
This should also be blue:
![2019-02-11_21-18-55](https://user-images.githubusercontent.com/4523551/52590920-db17cc80-2e42-11e9-844f-c3d581bfed06.png)
This is correct, how it should look.
![2019-02-11_21-19-03](https://user-images.githubusercontent.com/4523551/52590943-e7038e80-2e42-11e9-8ccb-8877d63b8777.png)

I'm not asking you to fix or support anything you don't feel like, I just want to make my issue clear and then you can make a call how much work this is or not.

**Comment by stonecrusher** [comment]
I've made a [PR](https://github.com/overdodactyl/ShadowFox/pull/246) which should fix it back to the original uBO colorblind colors.

**Comment by SheepKid12** [comment]
Looks like the element picker went back to being white.

![image-thing-whatever](https://user-images.githubusercontent.com/8013408/52749046-bc821480-2fad-11e9-91d6-15565bfa7acb.png)

**Comment by stonecrusher** [comment]
@SheepKid12 Can't reproduce. You probably didn't use [the new version](https://raw.githubusercontent.com/stonecrusher/ShadowFox/patch-2/css/userContent-files/webextension-tweaks/ublock_origin.css) of ublock_origin.css?
