### ISSUE TITLE
uBlock Origin power button always grey

### ISSUE THREAD

**Issue by xmaestro21** [overdodactyl/ShadowFox#239]
The big power button in the uBlock Origin Interface always stays grey. Usually it would be blue when it's turned on, but now it is grey no matter if it's turned on or off, and you can't tell the difference

![unbenannt](https://user-images.githubusercontent.com/21089903/51788218-bd2c4580-217b-11e9-9d0d-a8cbc35bf3da.png)

Would appreciate if you look into this, thanks.

**Comment by overdodactyl** [comment]
Thanks for the report @xmaestro21! The power button has a temporary fix.

There have been a lot of UI changes to uBO that need a better long term fix, which I'll be addressing ASAP in #236 as well.
