### ISSUE TITLE
Can't uninstall ShadowFox

### ISSUE THREAD

**Issue by n-o-o-b** [overdodactyl/ShadowFox#242]
I recently noticed that ShadowFox causes the ticks in the tickboxes in the browser's Options to become invisible (I'll open another issue for this), so I downloaded ShadowFox again to see if I could update it (in case there had been an update released which had fixed the issue). The tickboxes issue wasn't fixed, so today I decided to temporarily uninstall ShadowFox so I could change some settings in Options and see the tickboxes, but it hasn't uninstalled. Could this be because I ran the installer twice? Help needed.

**Comment by n-o-o-b** [comment]
Edit: never mind. Turns out I had the wrong profile selected. The field next to the profile was blank, so I didn't realise it had the wrong one selected.

**Comment by n-o-o-b** [comment]
actually no my browser seems to be in some weird halfway state

**Comment by RepoPOD202** [comment]
Ehh.. sorry that  that happened

**Comment by stonecrusher** [comment]
Try to delete it manually and start over fresh.
The files are in your profile folder:
- enter `about:support` into addressbar
- click "open folder"

If you don't have other modifications, just delete the "chrome" folder inside your profile folder.
If you have other modifications, you probably know which parts to delete. At least the ShadowFox folder.

**Comment by n-o-o-b** [comment]
> 
> 
> Try to delete it manually and start over fresh.
> The files are in your profile folder:
> 
>     * enter `about:support` into addressbar
> 
>     * click "open folder"
> 
> 
> If you don't have other modifications, just delete the "chrome" folder inside your profile folder.
> If you have other modifications, you probably know which parts to delete. At least the ShadowFox folder.

That didn't work. :(

**Comment by stonecrusher** [comment]
> That didn't work. :(

Eeh if it's deleted, there is no way it can still work. You have probably only enabled [Firefox's own (incomplete) dark theme](https://www.youtube.com/watch?v=YrZhRxKzKts). Change it back to bright.

**Comment by n-o-o-b** [comment]
> 
> 
> > That didn't work. :(
> 
> Eeh if it's deleted, there is no way it can still work. You have probably only enabled [Firefox's own (incomplete) dark theme](https://www.youtube.com/watch?v=YrZhRxKzKts). Change it back to bright.

Changing between Default and Dark themes makes no difference. Only selecting Light changes it, but that's not the default one.

**Comment by SrKomodo** [comment]
can you post a screenshot of how your browser looks?

**Comment by n-o-o-b** [comment]
![browser1](https://user-images.githubusercontent.com/19697175/52904312-1428b600-3222-11e9-8658-4c32cc525245.png)
![browser2](https://user-images.githubusercontent.com/19697175/52904313-14c14c80-3222-11e9-86b3-5650d522b3fd.png)
![browser3](https://user-images.githubusercontent.com/19697175/52904314-14c14c80-3222-11e9-9cc6-54d2b5f01b47.png)

**Comment by overdodactyl** [comment]
This looks like normal Firefox behavior, and not due to anything ShadowFox related

**Comment by n-o-o-b** [comment]
> 
> 
> This looks like normal Firefox behavior, and not due to anything ShadowFox related

What normal Firefox behaviour specifically? And do you know how to return it to how it was?

**Comment by overdodactyl** [comment]
>What normal Firefox behaviour specifically?

Those are built in Firefox themes, ShadowFox is not styling anything in those photos.  

>And do you know how to return it to how it was?

What is it you want to change?

**Comment by n-o-o-b** [comment]
> What is it you want to change?
The Default theme used to (and as far as I understand, still does) look like this:
![image](https://user-images.githubusercontent.com/19697175/52904739-29a0de80-3228-11e9-95eb-c4bf30115fe7.png)
Mine doesn't.

**Comment by overdodactyl** [comment]
They've been making some changes to what the default is depending on your computer settings/themes, this may be a cause of that.

But in any case, ShadowFox doesn't style that portion of the browser, and there's no way it could be effecting anything if you've deleted the files and restarted the browser.

**Comment by n-o-o-b** [comment]
Oh, okay, I see. I'll have to do some research then, or just simply reinstall. Though it doesn't bother me too much. Thanks anyway.

I'll get round to reporting that bug I mentioned in my 1st message when I reinstall ShadowFox.

**Comment by doronbehar** [comment]
I was hit by this as well, with a new profile installed and everything, and apparently it was my GTK theme affecting what Firefox considers as default.
