### ISSUE TITLE
Waterfox

### ISSUE THREAD

**Issue by sutex** [overdodactyl/ShadowFox#244]
Unable to install ShadowFox using Waterfox

I'm a FT DeepDark  Mozilla refugee :(

**Comment by Riajyuu** [comment]
@sutex many clasdnames of these CSS rules are from Firefox 57+, but waterfox is a fork of gecko 56. I think that's why you encounter this.

**Comment by overdodactyl** [comment]
As @Riajyuu said, if Waterfox is a fork of 56, ShadowFox won't likely work very well, even if you get it installed properly.

Based on the user base, I unfortunately I probably can't justify the work to get ShadowFox compatibility on Waterfox as well.

**Comment by sutex** [comment]
No worries kinda have FT DeepDark installed with Waterfox, but there's issues as long as the wheels don't fall off, all good.
