### ISSUE TITLE
raw.githubusercontent.com

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#248]
Doesn't seem to work anymore in FF 65, although applied correctly.
However it *does* work when using absolute colors instead of variables:
```
@-moz-document url-prefix(https://raw.githubusercontent.com) {
  html {
    background: #38383d !important;
    color: #b1b1b3 !important;
  }
}
```

Example: https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Full%20dark%20theme/scrollbars.as.css

**Comment by overdodactyl** [comment]
Thanks for the report - should be fixed
