### ISSUE TITLE
Text at top of Get Add-ons tab is broken.

### ISSUE THREAD

**Issue by thakyZ** [overdodactyl/ShadowFox#249]
I am running on Windows 7 and Firefox Stable 65.0.1

This happens when using the latest Shadowfox. I tried removing my modifications in the ShadowFox_customization folder, and still no changes as far as I can see.

This is a picture of the issue:   
![image](https://user-images.githubusercontent.com/950594/53256484-db06a080-367c-11e9-82f5-2c99d0a41ddb.png)

**Comment by overdodactyl** [comment]
Thanks for the report!
