### ISSUE TITLE
Extension info from context menu in about:addons is not themed

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#25]
when you right click an add-on in the extensions page and then click About, the page it shows is not dark themed.

# [Example](https://image.prntscr.com/image/SKW_hfoPTzOaqylrO8o_rg.png)

**Comment by xAphex** [comment]
@overdodactyl 
also found another bug:
[Image](https://image.prntscr.com/image/MkACzPU0Tn2E5gqlYrzsOA.png)

this menu here doesn't highlight when you hover over it.
also the white dividers should be dark i believe.

**Comment by xAphex** [comment]
one last thing, how do i change the padding between the text here?
# [Image](https://image.prntscr.com/image/OzUm6lqbT4KP_rHQxQLO6g.png)

**Comment by overdodactyl** [comment]
Same fix as the other one (nearly identical code is used in the `amo_store.css` file for context menus.  I'll get an update with that fix to the repo asap

**Comment by xAphex** [comment]
@overdodactyl nothing is in amo_store.css but i found the same code in addons.css
after adding padding-top & padding-bottom, nothing has changed.

## line 143 in addons.css

`  	menupopup menu, menuitem {
    	-moz-appearance: none !important;
    	color: var(--grey-10) !important;
  	}`

i made it like this:

`  	menupopup menu, menuitem {
    	-moz-appearance: none !important;
    	color: var(--grey-10) !important;
		padding-top: 4px !important;
		padding-bottom: 4px !important;
  	}`

**Comment by overdodactyl** [comment]
Oh, sorry...mistake on my part.  Gave you the wrong file name :/

Thanks though, that looks good.  I'll try and incorporate something like that in soon!

(Apologize for the lack of updates lately, have been fairly bust)

**Comment by overdodactyl** [comment]
I'm unfortunately not seeing an easy way to change those little pop-ups.

I have a feeling those aren't very widely used, however, so I don't want to invest too much more of my time looking into them.

As always, if someone else figures it out, I would accept a pull request.

I do appreciate you letting me know about the issue, however.

**Comment by xAphex** [comment]
@overdodactyl i fixed the problem, turns out i put everything in github repo in chrome folder, u only need `usercontent.css` and `userchrome.css`, all this time i was just editing `addon.css`.

i made a pull request with the fix included.
