### ISSUE TITLE
Contrast too low for Disabled addons

### ISSUE THREAD

**Issue by opav** [overdodactyl/ShadowFox#255]
In my list of addons at about:addons, disabled items fonts is too dark and difficult to see.  

Can the disabled items font color be set to the same level as the enabled items, the darker background is enough to tell them apart.

![](https://i.imgur.com/K5Li2Fo.png)

Or is there a diy method for me to exclude the about:addons page from dark styling?

**Comment by overdodactyl** [comment]
Hi @opav -I've add brightened the color a bit in the latest version.
