### ISSUE TITLE
about:reader themes are overridden

### ISSUE THREAD

**Issue by Zlewness** [overdodactyl/ShadowFox#26]
Pressing the reader view on supported pages forces a dark theme on all pages. I know this is meant to be the point of this theme, but the reader has its own dark theme ability, and it is rendered useless. The following code is too broad and doesn't exclude about:reader, commenting it out allows changing light-dark-sepia

> @-moz-document url-prefix(about:), url(https://www.mozilla.org/credits/) {  
  html:not(#ublock0-epicker), html:not(#ublock0-epicker) body, #newtab-customize-overlay {
    background: var(--primary-dark-color) !important;
    color: var(--primary-light-color) !important;
  }  
  
>  a:link {
    color: var(--primary-accent-color) !important;
  }
}

**Comment by Zlewness** [comment]
Okay I'm not absolutely certain about this but if you replace line 111 in userContent.css from

`@-moz-document url-prefix(about:), url(https://www.mozilla.org/credits/) {`

to

`@-moz-document url(regexp("^about:(?!reader)"))` it seems to fix the issue

**Comment by overdodactyl** [comment]
Hi @Zlewness, thanks for bringing this to my attention! That was an oversight on my part.

I'll test the code you kindly provided, but I _think_ that should work (I need to brush up on my regular expressions..)

**Comment by overdodactyl** [comment]
Looks like if we change it to 

`@-moz-document regexp("^about:(?!reader).*")` we get the intended matches
