### ISSUE TITLE
Bad contrast on new tab

### ISSUE THREAD

**Issue by luispabon** [overdodactyl/ShadowFox#263]
First of all, thank you for the hard work, stuff is looking real nice. A few niggles though:

  * black text on gray background (top sites)
  * black text on gray background (search)
  * unstyled "messages from firefox"

FF 66.0.5, Ubuntu 19.04

![image](https://user-images.githubusercontent.com/6388823/57984643-c6f0f600-7a55-11e9-8b25-8b59a21bfeb9.png)

**Comment by overdodactyl** [comment]
Hi @luispabon! Thanks for reporting these! I'm not actually seeing this on my end though, I'm wondering if you have the default dark theme provided by Mozilla selected?

Hamburger menu > Customize > Themes > Dark

**Comment by luispabon** [comment]
I did indeed. Upon disabling it (rather than selecting another one), I get a similar result:

![image](https://user-images.githubusercontent.com/6388823/57987499-07626b00-7a7a-11e9-9ecf-aff81a38b38b.png)

**Comment by overdodactyl** [comment]
Not seeing this issues under the current version; please re-open if you find that not to be the case.

Thanks
