### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by M86xKC** [overdodactyl/ShadowFox#265]
I'm new to this project.

So can someone explain the status of the project, because I have not seen any activity recently.

Is it not maintained anymore?

Because I have noticed some issues in the right-click menu & other panels & new home page

To solve these issues I would appreciate some documentation If there is any ?

**Comment by overdodactyl** [comment]
It is still maintained.

If you're running into problems the best thing to do is look through the open issues.  If you see the same problem you are having you are welcome to contribute to the conversation there.  Otherwise you can open a new one with the requested info in the issue template.
