### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#27]
I received a lot more negative feedback about my color choice of darkcyan than positive.  So, by popular request, I decided to use a dark orange ([orange 70 and 80](https://design.firefox.com/photon/visuals/color.html)).

Users seemed to like this because it was (a) more inline with Firefox colors and (b) darkcyan didn't show up well for f.lux users.

The color scheme is naturally going to be a highly personal choice, so bear in mind it won't be possible to please everyone, but the goal here is the majority :)

For those who don't like the colors chosen, they can easily be modified in either [color_variables.css](https://github.com/overdodactyl/ShadowFox/blob/master/color_variables.css) or the first section of your userChrome/userContent.css files (depending on how you are using this repo).

As always, feedback and suggestions are welcome.

**Comment by overdodactyl** [comment]
![settings](https://user-images.githubusercontent.com/33071129/33954606-a73c5270-e030-11e7-9a9e-81fcb18bbf33.png)
![adressbar](https://user-images.githubusercontent.com/33071129/33954609-a8d9da8a-e030-11e7-93bc-762fd495b94b.png)

**Comment by xAphex** [comment]
i like the darkcyan, it fits well with the dark theme.

maybe a tutorial on how to change the color scheme would be cool.

**Comment by overdodactyl** [comment]
Thanks for the input @xAphex :) I too like the darkcyan look...orange is growing on me as well though.

I can certainly put together a little wiki tutorial on changing the color, that's a good idea. 

Perhaps adding a little script to automate the process would be a good idea as well 🤔

**Comment by imatimba** [comment]
I prefer the darkcyan too, but whatever the majority prefer is ok.

**Comment by overdodactyl** [comment]
Damn, maybe I let all the Reddit folks guide me in the wrong direction haha. 

Thanks for the input @imatimba :)

**Comment by junnu-github** [comment]
I prefer the darkcyan too.. 
"Create variable so users can easily change the theme" this would solve i guess..

**Comment by RadWoodward** [comment]
I honestly just think a brighter orange would be better. right now it looks like burnt orange, and it's a little hard to read against the dark background

**Comment by azizLIGHT** [comment]
I'm sorry it looks like poo right now. How do I change it to what you have in the screenshots...

**Comment by overdodactyl** [comment]
Hmm perhaps I'll revert it back to the darkcyan and add some additional color options in a commented out section people can choose from.

@junnu-github, they are variables already :)

@RadWoodward, I'll play with some various orange shades...thanks for the feedback

If anyone's interested in the script idea as well, let me know and I'll throw that together as well.

**Comment by CaptaPraelium** [comment]
Well, you probably already know that I've been running blue-50 since that was the dark theme's default tab highlight colour and it clashed with the dark cyan, and since, I've found that it also blends well with the blues that tend to appear elsewhere (Blue hyperlinks are the norm in other apps, Logitech blue, Microsoft likes blue highlights, even if your colours are all set to black and grey, you see blue in context menus everywhere such as NP++, blue in many of the windows icons, blue in discord, etc etc.)

Perhaps not necessarily this particular shade (blue-50) but some shade of blue might be preferable.

Sorry to go offtopic, but speaking of f.lux, here's a preferable alternative you may like: https://github.com/Tyrrrz/LightBulb
Not only open-source, but superior performance which considers a gamer's use-case. 
More info here; https://www.reddit.com/r/osugame/comments/5rpq1q/lightbulb_gamingfriendly_flux_alternative/

**Comment by overdodactyl** [comment]
@CaptaPraelium, blue's not a bad idea either, I'll look into that (too many options :grimacing:)  What was it you used with blue-50...blue-60/70?

Lightbulb looks interesting! I'll be giving it a try tonight :) 

Perhaps as a wiki page it would be cool to add a few suggestions like LightBulb/f.lux, an extension for Firefox dark page extensions etc.

**Comment by CaptaPraelium** [comment]
I'm using blue-60 with it at the moment but I haven't really tinkered with it a lot. It just kinda fell that way and there it is. There may be better options.

Oops I keep forgetting the whole cross-platform thing, my bad! I use http://jonls.dk/redshift/ on linux, the package managers usually have it and its GUI ready to go.

Speaking of Windows only, it did occur to me that the blue everywhere on my PC may be rather Windows-specific. In case you're curious: https://duckduckgo.com/?q=windows+explorer&iax=images&ia=images you can see the typical dominant colour on Windows.

I have a feeling that on Mac it's probably all beautiful and white and carved out of marble, and on linux everyone's DE will be different to the next guy... so maybe blue won't work so well.... 

Man, it's never simple is it? LOL

**Comment by overdodactyl** [comment]
Blue-50 does look pretty good on a mac as well.

But, no, things are never easy :( haha

Thatnls for the RedShift link, I'll check it out!

**Comment by sapierens** [comment]
I also prefer blue-50 over dark orange/cyan colors.

Any reason you like to go with so dark accent colors?
Personally something like this looks pretty good:
![](https://i.imgur.com/jTkkhfr.png)
![](https://i.imgur.com/ijL7HN1.png)

**Comment by overdodactyl** [comment]
@sapierens, thanks for the input.

As for the color choices, there were two main reasons:  (1) A lot of lighter colors made it too diffucult to read light text on top of it (in the case of buttons, search bars etc and (2) I was trying to adhere to Firefox's "official" Photon colors:

https://design.firefox.com/photon/visuals/color.html

What is that you're using in those screenshots? It looks too green to be the teal color panel they have

**Comment by overdodactyl** [comment]
I wanted to give `blue-50` a shot.

I'll wait and see if anyone has any opinions on that.

After giving this a try, I'll try and see what the most popular option was, make it the default and add any other options as commented-out code chunks people can easily switch too.

**Comment by sapierens** [comment]
> What is that you're using in those screenshots? It looks too green to be the teal color panel they have

That was just a random light color I tried, to showcase. I wasn't aware of the Photon color specification.

>A lot of lighter colors made it too difficult to read light text on top of it (in the case of buttons, search bars etc

I'd just change the color of text to dark or use a darker version of the accent for background.

When it comes to specification, seems like blue-50, magenta-50, red-50, purple-50 and grey-50 are the only somewhat light colors that work both as a text color and a background color for white text.
Out of those, obviously, blue-50 seems like the most sane choice, as it extends on the official Firefox's accent color.
As for trying to follow the official Photon color specification, doesn't look like they're completely adhering themselves:
![](https://i.imgur.com/N0PStML.png)

**Comment by overdodactyl** [comment]
@sapierensm, I think you're probably right, best solution might be to go with something a little lighter and change the text color/button color.  

You make an interesting point about them not adhering to their own theme...I didn't quite realize that.  

I currently switched it to blue-50, as I think that's a better short-term solution.  Do you think that's still a little too dark? 

This weekend I should have more time to tweak colors and the such.  

If anyone has any suggestions or colors they want thrown into the mix, feel free to let me know :)

**Comment by Mattwmaster58** [comment]
blue-40 looks ideal imo

**Comment by azizLIGHT** [comment]
Blue-50 and blue-60 the way you have it now seems pretty good!

**Comment by CaptaPraelium** [comment]
I think that blue-40 looks good on it's own, but it doesn't blend so well with the other blues that are so common in the system, as those are usually a 'royal blue' and blue-40 is more of a 'teal' kind of colour. For the same reason, blue-40 doesn't blend very well with either blue-50 or blue-60.

**Comment by ShahedFaisal** [comment]
[This line](https://github.com/overdodactyl/ShadowFox/blob/9b53ac38494715679b2c6c9117acfbd64762428a/userChrome-files/dark_nav_bar_menus.css#L67) still has darkcyan as the color. Should be changed.

**Comment by overdodactyl** [comment]
Thanks @ShahedFaisal! 

It's now been changed
