### ISSUE TITLE
Does this work on Firefox Developer Edition?

### ISSUE THREAD

**Issue by lukeberry99** [overdodactyl/ShadowFox#275]
Does this work on Firefox Developer Edition? I've installed it and the updater showed me three profiles (bunch of text, no idea which one is the actual one) so I instlaled it on all three, restarted the browser and there is no culpable difference between this and the previous dark theme.

Am I doing something wrong or is the developer edition not supported?

Cheers.

**Comment by SrKomodo** [comment]
Open `about:profiles` in dev edition and look up the root directory of the profile in use, then open shadowfox and see if that profile shows up on the list.
While you are at it, which OS are you using?

**Comment by lukeberry99** [comment]
The profile is there, the install doesn't seem to do anything - what's the best way to confirm it is installed?

I'm using macOS Mojave 10.14.6 Beta

**Comment by SrKomodo** [comment]
> what's the best way to confirm it is installed?
go back to `about:profiles`, click "Open Directory" on the profile in use, then look for a folder named `chrome` that should have a `ShadowFox_customization` folder inside if Shadowfox was actually installed.

**Comment by XedMada** [comment]
Firefox v69 disables userChrome by default now. In `about:config` change `toolkit.legacyUserProfileCustomizations.stylesheets` to `true` and restart the app.

**Comment by LinnielDW** [comment]
> 
> 
> Firefox v69 disables userChrome by default now. In `about:config` change `toolkit.legacyUserProfileCustomizations.stylesheets` to `true` and restart the app.

For anyone else who comes across this, this worked for me.
Using Version 69.0b6 (64-bit).

**Comment by overdodactyl** [comment]
>toolkit.legacyUserProfileCustomizations.stylesheets

I'll get that added to the wiki.

@SrKomodo, might be good to include in the updater wiki as well and possibly add it to the updater script itself if possible.

Thanks
