### ISSUE TITLE
Dark Theme Enhancing Extensions and User Styles

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#28]
I think it would be nice to put together a wiki entry with suggestions/links to things that can further enhance this repo's goal of a "universal dark theme."  I figured I would start off a list here, and hopefully get some thoughts from everyone else out there.

## System-wide
- [f.lux](https://justgetflux.com/)
    - Mac, Windows, Linux
- [LightBulb](https://github.com/Tyrrrz/LightBulb) (thanks @CaptaPraelium for the recommendation #27)
    - Windows only

## Firefox Extensions
- [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/) (again, thanks @CaptaPraelium for the suggestion)
    - Let's you customize the background, text, link colors etc. to match the theme used in this repo

- [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)
    - implement custom userstyles (see below)
 
## Page Specific Userstyles

For times when an extension just can't do a good enough job

- [GitHub](https://userstyles.org/styles/37035/github-dark)

- [StackOverFlow](https://userstyles.org/styles/35345/stackoverflow-dark)

- [Bugzilla](https://github.com/overdodactyl/Bugzilla-Dark)
- [SUMO](https://github.com/overdodactyl/SUMO-Dark) (https://support.mozilla.org)

I'll try to continually update this issue and, ultimately, add this to wiki page.  If there are any things you guys use, please list below! :)

**Comment by CaptaPraelium** [comment]
This may be a little too specific, but I just stumbled across this theming for ProtonMail:
https://github.com/amdelamar/pm-theme

**Comment by overdodactyl** [comment]
Not too specific at all, thank you!!

I had actually been wanting to do something for ProtonMail but hadn't yet gotten around to it

**Comment by overdodactyl** [comment]
Add a new wiki page: https://github.com/overdodactyl/ShadowFox/wiki/Extending-the-Dark-Theme
