### ISSUE TITLE
Feature Customization

### ISSUE THREAD

**Issue by aemonge** [overdodactyl/ShadowFox#282]
Can you include my customization of moving the toolbar (nav-bar) to the bottom ?  I've seen you've included a few and thought that mine is cool too ;)

https://github.com/aemonge/dotFiles/blob/master/userChrome_customization.css

Cheers!

**Comment by overdodactyl** [comment]
Where are you hoping to get it included? The wiki is open for anyone to edit

**Comment by aemonge** [comment]
:) lol I complete forgot about that xD

I've changed the wiki al ready, thanks for the quick reminder ;)
