### ISSUE TITLE
scrollbar thumb very very barely visible

### ISSUE THREAD

**Issue by rinaldi6109** [overdodactyl/ShadowFox#283]
I just passed to FF 68 from 60ESR on a Win8.1 pc. I use Dark Reader addon in conjuction with ShadowFox theme.
When Dark Reader is in Dark mode, the scrollbar thumb is very very barely visible. [https://i.imgur.com/rrMEYQL.png](screenshot)
What can I add to userChrome.css to make it more visible?
Thanks.

P.S.: my userChrome.css is 98k, so I cannot report it. Anyway, it does not contain any occurrence of `scroolbar`. If requested, I will create a new empty profile.

**Comment by NomDeMorte** [comment]
That's a dark reader issue, but the wiki here does have links to alternative scrollbar code.

**Comment by rinaldi6109** [comment]
Where is the wiki here?

**Comment by NomDeMorte** [comment]
Just up there ^ Where is says "[Wiki](https://github.com/overdodactyl/ShadowFox/wiki)" ;)

The specific page which links to the dark scrollbar is https://github.com/overdodactyl/ShadowFox/wiki/More-Tweaks#dark-scroll-bars

But don't forget, this is just a workaround, you should file a bug report with Dark Reader.

**Comment by overdodactyl** [comment]
Thanks @NomDeMorte!
