### ISSUE TITLE
release of current version

### ISSUE THREAD

**Issue by ShalokShalom** [overdodactyl/ShadowFox#286]
the readme says you find the current version here in the release section, which is currently not the case

**Comment by overdodactyl** [comment]
The readme seems to correctly point to the release section of the shadowfox-updater repository

**Comment by ShalokShalom** [comment]
yep and it reads as if the current version would be released in this repo also: besides this, couple of people could just click on releases and download from there: i suggest to delete the two remaining old builds, so no confusion comes up
