### ISSUE TITLE
Themeing the snippet on about:home

### ISSUE THREAD

**Issue by Mattwmaster58** [overdodactyl/ShadowFox#31]
Would it be possible to theme the snippet on about:home?
The current config is light grey on slightly darker grey, making it unreadable w/o highlighting.
![SS of snippet on about:home for reference](https://user-images.githubusercontent.com/26337069/34057964-82ee5762-e196-11e7-98dc-f3c53cd86e12.png)

**Comment by overdodactyl** [comment]
Sorry about that!

Should be fixed now:

![snippet_text](https://user-images.githubusercontent.com/33071129/34058449-f1d3bf5a-e1d2-11e7-997c-f9491ae6e74f.png)

Let me know if that fixed it for you

**Comment by Mattwmaster58** [comment]
Looking good. Thanks!  :thumbsup:

**Comment by overdodactyl** [comment]
No problem! Thanks for letting me know :)
