### ISSUE TITLE
MC Forums comment section color bug

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#32]
i went browsing popular forums and websites looking for bugs because i was bored, then i stumbled upon a glitch/bug, basically two rules interfere with each other.

### MC Forums rule:
[compiled.css](http://static-minecraftforum.cursecdn.com/1-0-6490-23792/Skins/MinecraftForum/css/compiled.css) ((line 2))
```
html, button, input, select, textarea {
	font-family: sans-serif;
	color: #222;
}
```

### ShadowFox rule:
userContent.css ((line 112))
```
html:not(#ublock0-epicker), html:not(#ublock0-epicker) body, #newtab-customize-overlay {
	background: var(--primary-dark-color) !important;
	color: var(--primary-light-color) !important;
}
```

# Example: [Before](https://image.prntscr.com/image/lS8rRd2uSLy4uRfo2doTTA.png) | [After](https://image.prntscr.com/image/H2T9rJy5SsSsa_D6KwqZzg.png)

**Comment by overdodactyl** [comment]
Hmmm...that's interesting given the userContent rule you pointed to is contained within

`@-moz-document regexp("^about:(?!reader).*"), url(https://www.mozilla.org/credits/) {`

I unfortunately can't get to the comment screen without creating a steam account.

**Comment by overdodactyl** [comment]
I'll gladly accept a pull request for a fix here, but I unfortunately can't justify creating a Twitch and Minecraft account for this
