### ISSUE TITLE
How to setup updater on Mac?

### ISSUE THREAD

**Issue by barletta** [overdodactyl/ShadowFox#34]
Hi! Sorry, I couldn't quite figure out how to set this up. Could someone please write a tutorial on this? Thanks!

**Comment by overdodactyl** [comment]
Are you having trouble with getting `userContent.css` and `userChrome.css` to work or using the updater script?

**Comment by barletta** [comment]
I got those two working. How to use the updater script is where I had trouble!

**Comment by overdodactyl** [comment]
Right now the updater script is pretty simple and requires the installation of `git` on your computer.

Additionally, if you are using `gulp` to customize which snippets are included, that section needs to be uncommented and all the `gulp` requirements need to be installed as well (see [here](https://github.com/overdodactyl/ShadowFox/wiki/Customizing-what-tweaks-are-included-in-your-userChrome-and--userContent-files)).  

Essentially, the script simply calls `git pull` and whatever `gulp` commands you have set.

In the future, I will be looking to expand the capabilities of `updater`, including features such as:

- Not needing `git` if you are only using `userConent/Chrome` and not cloning the whole repo

- Providing options for changing the default color choice 

- ?? Not sure, we'll see if any other requests/ideas come up

To run the script on a mac, you should be able to simply double click it.
