### ISSUE TITLE
How to use ShadowFox - revisiting installation and updating

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#36]
As this project continues to grow, I think having an easy and clear method to (1) install and (2) update the project is increasingly important.  

I can imagine this project being used in a number of different ways by different users, and my goal would be to accommodate the various approaches.  

Some people may wish to use the entire repo, others only certain files, some may wish to change the default colors, in the case of webextension tweaks, the Internal UUID needs to be changed etc.

To complicate things, several Linux users reported a Firefox bug that prevents the proper usage of `@import` statements.  

As such, there are currently two versions of userChrome/Content in the repo (one that is all inclusive, and one that contains import statements).  Additionally, I recently included a "release" containing the two files.

Here's my initial thoughts on how people could approach installation:

![method](https://user-images.githubusercontent.com/33071129/34177377-4dfb98d6-e4fb-11e7-8df8-36e03f35da84.png)

and to accompany the various approaches, I would include updater scripts that would do the following:

![updater](https://user-images.githubusercontent.com/33071129/34177413-668ab4f4-e4fb-11e7-844e-2cd2667f32d2.png)

I'm curious how everyone is using this repo, and whether the approach/guide given above makes sense to everyone.

If you have any thoughts or suggestions, please leave them below!

Additionally, I may need some help righting the Windows equivalent of such a script (perhaps @CaptaPraelium would be interested? ;) )

**Comment by janhieber** [comment]
Sorry but this does not really help for installing this. I am an experienced Linux user and could not really figure out if I only should download the two user...css files and why there are so many node modules etc... 

Took a time till I realised that the repo should be cloned as "chrome" folder in FF profile directory.
Maybe an "Install" section with that would help.

**Comment by overdodactyl** [comment]
Hi @janhieber, thanks for the comment! I'm currently working on a little write-up for installation and updating.  I'll let you know when it's complete.

This was more to hopefully get an idea on what type of functions an `updater` script should have, or if even anyone would benefit from that.

The node modules are needed to run `gulp`, which concatenates a defined set of `.css` files.  See [here](https://github.com/overdodactyl/ShadowFox/wiki/Customizing-what-tweaks-are-included-in-your-userChrome-and--userContent-files) for more info on that.

**Comment by overdodactyl** [comment]
@janhieber, I've added a new wiki page that hopefully will help straighten things out:

https://github.com/overdodactyl/ShadowFox/wiki

it's still a work in progress, but hopefully a good start :)

**Comment by CaptaPraelium** [comment]
Sorry, only just saw this. Definitely will write anything you need, I owe you some time, you did save my retina after all ;)
