### ISSUE TITLE
1px off on Password save popup

### ISSUE THREAD

**Issue by Mattwmaster58** [overdodactyl/ShadowFox#40]
See screenshot.  The separator between the 'don't' save and 'v' button sticks out.

Couldn't find the ID with browser toolbox.
![capture](https://user-images.githubusercontent.com/26337069/34280529-6da4e996-e675-11e7-98b6-47b5a64d1836.PNG)

**Comment by xAphex** [comment]
where do u find that password menu? link?

**Comment by overdodactyl** [comment]
@Mattwmaster58, I'll see what I can do.  That appears to be an issue coming from FF, however, not the styling I've done as it's noticeable in a non-styled profile as well:

![screen shot 2017-12-22 at 3 54 00 pm](https://user-images.githubusercontent.com/33071129/34314386-261566cc-e76b-11e7-91ae-c373a1812c28.png)

**Comment by overdodactyl** [comment]
Looks like FF fixed it:


![password](https://user-images.githubusercontent.com/33071129/34555132-1461cf44-f128-11e7-8131-5983bbd6eaa4.png)
