### ISSUE TITLE
uBlock Origin Dark theme does not work

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#43]
I checked the commits and saw that you added dark theme support for uBlock Origin.
When i updated, uBlock Origin was the same as before.

Turns out that you have a different URL set. (`@-moz-document url-prefix("moz-extension://de835161-ee69-c14d-9940-203fbacf2276/") {`)

### The URL prefix for me is: `moz-extension://97bdeb2a-2183-4420-bc51-b5557a6f3a45/`

I guess the that URL changes from person to person.

P.S, the URL is a GUID/UUID that identifies the the extension.

**Comment by overdodactyl** [comment]
Unfortunately the Internal UUID does change for each install.

See here for a little more info:

https://github.com/overdodactyl/ShadowFox/wiki/ShadowFox-is-incompatible-with-the-preferences-page-of-one-of-on-my-addons#workaround

I've been considering writing a better `updater` script that would automate the process of changing the UUID automatically, but there hasn't seemed to be much interest, so I've kinda put it on the back burner: https://github.com/overdodactyl/ShadowFox/issues/36

FYI: I'm still tweaking with the look for uBO, so it should be looking better soon :)

**Comment by xAphex** [comment]
so um, idk if this bug is from my uBO or Firefox, or it's your script, but the uBO themed doesnt theme everything.

i checked the code and your theme has the right code, but it still doesnt theme it, for example:

uBO's extra tools are not themed, but when i checked the code, they are supposed to be themed.

## `userContent.css, line 1010`:
### the code is there, but it's not themed.
### [Image](https://image.prntscr.com/image/c2XHdVkBTvyuonPYnqp1eA.png)

**Comment by overdodactyl** [comment]
@xAphex,

That's weird the bottom section is getting styled for you.

Interestingly someone else wrote a different dark-mode versions for uBO and posted it on Reddt:

https://www.reddit.com/r/FirefoxCSS/comments/7lefac/ublock_origin_dark_theme/

From the comments section, it appears people are having the same issue you are reporting here

**Comment by overdodactyl** [comment]
Given extratools are being themed in most cases and is styled via ``uBlockOrigin.css`, I can only assume this is due to some sort of bug as you suggested.

If anyone finds a solution, feel free to let me know, but otherwise there's not much I can do here.

**Comment by overdodactyl** [comment]
Merging with #42
