### ISSUE TITLE
Theming #automaticallyReportInFuture + #learnMoreLink

### ISSUE THREAD

**Issue by Mattwmaster58** [overdodactyl/ShadowFox#46]
#automaticallyReportInFuture (checkbox) isn't themed. (pure white)
#learnMoreLink isn't themed (dark grey on lighter grey)

See screenshot

![screenshot](https://user-images.githubusercontent.com/26337069/34329905-72a07a30-e8cf-11e7-8744-d8d3a5f44e57.PNG)

**Comment by overdodactyl** [comment]
When do you see these pop up?

**Comment by Mattwmaster58** [comment]
It's the 'Secure Connection Failed' page if that's what your asking

**Comment by overdodactyl** [comment]
Do you happen to know a site I can visit to get that?  I seem to get this page:

![screen shot 2017-12-26 at 6 30 46 pm](https://user-images.githubusercontent.com/33071129/34367689-a8fd9b58-eaa5-11e7-8c93-eeed2d7b6be2.png)


If not, no worries...I can just wait until I stumble across one

**Comment by Mattwmaster58** [comment]
I know the error code is different. Repoducing the page is kinda hard though (;

**Comment by overdodactyl** [comment]
Figured so - I'll keep my out for it

**Comment by overdodactyl** [comment]
If anyone could give me a link were they see this, that would be great....have yet to come across it myself haha

**Comment by mattjudge** [comment]
This seems to be the same type of error @Mattwmaster58 was receiving: https://untrusted-root.badssl.com/. Note that the "Learn more..." pictured below is after clicking it.

![image](https://user-images.githubusercontent.com/3685915/35773395-c5078ea0-0948-11e8-9441-10bf9c30685b.png)

**Comment by overdodactyl** [comment]
Looks like that's it! Thanks for the link, really appreciate it :)

Should be fixed now.
