### ISSUE TITLE
Invalid cert dialog not themed

### ISSUE THREAD

**Issue by CaptaPraelium** [overdodactyl/ShadowFox#48]
A picture says 1000 words ;)
![image](https://user-images.githubusercontent.com/22152831/34529755-1f067368-f101-11e7-8796-0255509e054e.png)

@overdodactyl offtopic: since this script is working so well now, I find myself visiting this page less often. If you need a hand with any windows-specific stuff, feel free to email me to get my attention.

**Comment by overdodactyl** [comment]
Thanks @CaptaPraelium! Any chance you could share the specific url you ran into when getting that message?

I tried visiting just www.tawbaware.com, but didn't get it.

If not, no worries, I might just have to wait to fix it until I stumble across it.

And thanks for the offer! I'm still debating what to do with that updater script idea haha.  Not many people have expressed toooo much interest in it, so I'm curious if people have just figured out their own ways to update/make modifications that their happy with, there just aren't many people visit this issues page and didn't see the topic or what

**Comment by CaptaPraelium** [comment]
Sorry, 
 https://www.tawbaware.com/
Does that do it?

**Comment by overdodactyl** [comment]
>Does that do it?

Yep! Should be fixed now :)

Per usual, let me know if it didn't work or don't like the look or something and I'll re-open
