### ISSUE TITLE
White flashes

### ISSUE THREAD

**Issue by CaptaPraelium** [overdodactyl/ShadowFox#49]
Sorry, I know this one has been done before, and I'm not sure if there's any more that can be done with the CSS files here but, I'm still seeing white flashes when loading.

I came across a discussion of this on reddit https://www.reddit.com/r/FirefoxCSS/comments/7mm574/how_to_stop_the_flashing_white_screen_when_i_open/

Ironically, reloading that page is an example of a page where I see the flashes.
Our hero had posted there suggesting a script with stylus.... I tried that and still get the same.

Perhaps of interest, when I went to grab that link, I hit CTRL+H to open history, and noticed I'm even seeing a flash there as the sidebar loads. 

I know that there is already CSS in place to stop this so I'm fearing that it might just be a firefox 'feature', but if anyone has any ideas, I'd be keen to try them out.

Thanks :)

**Comment by overdodactyl** [comment]
Just as a quick sanity check, does your Stylus script look something like this (ignore the second snippet)?

![reddit_flash](https://user-images.githubusercontent.com/33071129/34537909-2080e7da-f0c2-11e7-99d7-02abe8c1d51a.png)

Things to check 

(1) Where the Stylus script applies (`URLs starting with https://www.reddit.com`)

(2) Maybe try changing var(--primary-dark-color) to a hex color as shown in the photo.  I was honestly kinda surprised I was able to use the variables and not sure where they are getting picked up from (not sure if Stylus sees the ones from ShadowFox, I defined them in another style somewhere that they are getting used from etc.)

>Perhaps of interest, when I went to grab that link, I hit CTRL+H to open history, and noticed I'm even seeing a flash there as the sidebar loads.

I believe this is a different issue than the one you are seeing with webpages, and one I haven't looked into quite yet. I will do so, however, as I've noticed that as well.

**Comment by CaptaPraelium** [comment]
Aha, you've given me just the tips I needed to pinpoint the problem. TL;DR it is not your code, Sorry to have bothered you with this! (I do still have the flashes when opening history, but I'll leave that to you)


So, this is all I have in stylus right now (and after this I don't think it is needed at all, but I'll explain that shortly)
![image](https://user-images.githubusercontent.com/22152831/34540246-f52bb0f4-f127-11e7-82cd-3a543267be89.png)

I tried changing the colour to #000000 just for testing, and when I clicked save in stylus, I could immediately see the colour change to black. So, I tried that reddit page again and... still white flashes.

So, I changed the colour to #00f000, like zombie green. Refreshed the reddit page again and... still white flashes.
Next, I visited a site I know has a dark theme by default: https://symthic.com/ and... green flash!

This got me to wondering, why am I seeing the white flash on one website but the green flash on another? So, I disabled the stylus script, reloaded the symthic site, and got a grey flash - so, the ShadowFox code is working as intended there....but I still got the white flash on reddit.

That's when I realised that the problem is with the extension that I am using for theming pages dark. The plugin offers three modes of theming pages, and one is a 'stylesheet processor'. On the symthic.com site, I have that script disabled because it is dark natively. With other modes (invert, simple CSS), I do not get the white flash on the reddit page. It seems that regardless of my userchrome/usercontent CSS and regardless of stylus scripts, the stylesheet processor is inserting some white background.

I hope it's OK that I link this bug to that developer so he can have the full context of this situation?

**Comment by overdodactyl** [comment]
Honestly it's not a bother at all! It's good info to have, and I'm glad you linked the bug for the dev. 

I'll keep my eye on it and see if anything ends up happening with it.  

It's good you were able to figure out the issue, I'm not sure I would have thought of that right away haha.

P.S., I'm working on code for the Stylus page since it doesn't look great at the moment:

![stylus](https://user-images.githubusercontent.com/33071129/34541956-420d1a94-f0d2-11e7-9f95-c879e555a2ad.png)

I'm trying to match the colors/design to FFs dark mode for the inspector/browser toolbox.  

Still a work in progress...but it's coming along!

**Comment by CaptaPraelium** [comment]
Oh, looking good! I noticed it didn't look quite right but I didn't want to trouble you with it.... but as usual you are treating us all to a better experience. I really appreciate your work mate!

**Comment by overdodactyl** [comment]
Thanks, I appreciate that!

And honestly it's no trouble at all, if you (or anyone for that matter), come across things that should be changed I'd like to know about it!

Can't always guarantee I'll be able to get a fix out right away, but I'll leave the issue open until it is!

**Comment by overdodactyl** [comment]
Any opinions on something like this?

![stylus](https://user-images.githubusercontent.com/33071129/34545316-1b2dc826-f0e4-11e7-8cf0-1c63b4c990b6.png)

**Comment by CaptaPraelium** [comment]
Looks great! The only thing that stands out is the serifed font.

**Comment by overdodactyl** [comment]
I'm not very good with my fonts haha...do you mean the text in the editor or the settings text?

**Comment by CaptaPraelium** [comment]
Yeh it's all in the settings text actually... I'm guessing that's hard-coded into the extension?

![image](https://user-images.githubusercontent.com/22152831/34546740-0aad22ec-f14a-11e7-9954-4491ac646278.png)

**Comment by overdodactyl** [comment]
It is coming from the extension, but it looks like if I change it to `font-family: arial,sans-serif !important;` we get a match for the two fonts:

![fonts](https://user-images.githubusercontent.com/33071129/34547002-dd460f1c-f0ef-11e7-8c5c-e5ec52858e11.png)

**Comment by CaptaPraelium** [comment]
You make me want to learn CSS. Great work!

**Comment by overdodactyl** [comment]
Thanks! And it's a lot easier than one might expect :)

I'll get this uploaded to the repo later tonight hopefully

**Comment by overdodactyl** [comment]
I've uploaded the initial code for Stylus if you wanna give it a try.

You'll have to switch the Theme to default for it to completely go into effect.  Once I get the text  editor colors more finalized, I may try and submit a PR to Stylus and see if they will include a "Photon-like" color scheme - that way my edits wouldn't have to override one of the currently available ones

**Comment by overdodactyl** [comment]
FYI: I've opened an issue with Stylus to see if there would be interest in `firefox-dark` theme:
https://github.com/openstyles/stylus/issues/323

**Comment by overdodactyl** [comment]
@CaptaPraelium, the white flashes in the sidebar that you mentioned should now be fixed.  

I don't see anything occurring on the bug you linked to with the extension, but I'm not sure there's much I can do there.

Closing this, but please open up a new issue if you see white flashes in other locations :)  (recent fix should have taken care of tabs and sidebar)
