### ISSUE TITLE
Missing moz-document

### ISSUE THREAD

**Issue by synthtech** [overdodactyl/ShadowFox#52]
The lack of a `@-moz-document` rule in this file [here](https://github.com/overdodactyl/ShadowFox/blob/a0703207b472efae7751617c3d60fd4bfe1801ab/userContent-files/webextension-tweaks/multi_account_containers.css) is causing the styles to apply to every webpage I visit.

**Comment by overdodactyl** [comment]
Thanks @synthtech! Should be fixed now :)
