### ISSUE TITLE
Dark theme for NoScript

### ISSUE THREAD

**Issue by qazip** [overdodactyl/ShadowFox#56]
Hello,

It would be nice if shadowfox provided a dark-theme for NoScript.

**Comment by overdodactyl** [comment]
Hi @qazip,

I don't use NoScript, so I may have missed some aspects of the UI/settings.  Please give it a try and let me know if I've missed anything or if you would like to see anything changed. 

Per usual, only tested on a mac.

**Comment by overdodactyl** [comment]
Closing, but feel free to let me know if you run across any problems.
