### ISSUE TITLE
Dark texts

### ISSUE THREAD

**Issue by blank15927** [overdodactyl/ShadowFox#57]
Hi
Thanks for this great theme. Amazing job !

A small problem : when I open the Bookmarks Libray, buttons at the top of the window are black on dark.
See picture (in french in my case).

![20180115 095453](https://user-images.githubusercontent.com/35070636/34937010-957e08ea-f9e3-11e7-8105-25c67a3dbd22.png)

I tried to find something in your "libray.css", but no luck.
Maybe it's just me. In this case, maybe you could tell me which selector to use.
(When I use browser chrome and add-on debugging toolboxes, it seems I can't make any selection in the Bookmarks Libray panel ?)

Same goes for the little popup appearing when clicking "Save to Pocket" : some texts are dark on dark.
![20180115 101524](https://user-images.githubusercontent.com/35070636/34937020-9cde306a-f9e3-11e7-826c-db3503a3a36e.png)

Thanks again for your work !

**Comment by overdodactyl** [comment]
Hi @blank15927,

I'm glad you're enjoying the project!

And thanks for bringing these to my attention! I don't use all of FF's features (such as Pocket), so it's easy to miss things like this unless it's pointed out :)

I think the pocket popup should be taken care of:

![pocket](https://user-images.githubusercontent.com/33071129/34954602-f12f3698-fa18-11e7-81c7-effa9dd92961.png)

but, as I mentioned, I don't really use it, so if I missed anything, please feel free to let me know.

By the way, did you style the pocket popup by yourself at all? When I first opened it, it had a white background, which was different than your screenshot.

I'm a little confused on the Library, however.  Did you do something special to make the labels/text show up?

This is what my bookmarks top bar looks like in the Library:

![bookmarkspanel](https://user-images.githubusercontent.com/33071129/34954693-52b9a5e2-fa19-11e7-93fa-83b54ea2cbb2.png)

and I'm not seeing any settings to add the labels.  I should probably work on styling the buttons though.

BTW, you can't use the broswer toolbox normally to inspect the Library dialog.  To inspect it, go to ` chrome://browser/content/places/places.xul` via the address bar, then use the browser toolbox on the resulting page.

**Comment by blank15927** [comment]
It's perfect for Pocket. Thanks !
Just in case : it seems to me you didn't add an import line in "userContent_imports.css" for pocket.css ?
I just added it in my userContent.css and it works nicely.

And no, I didn't do anything to the Pocket popup. I thought it was your theme. Or maybe native Firefox Dark Theme ? I don't know.

As for the labels in the Library window, I didn't do anything.
AFAIK they have always been there.

Thanks for the tip, I figured out how to change the color  : 

```
@-moz-document url(chrome://browser/content/places/places.xul) {
    #placesMenu > menu {
        color: var(--primary-light-color) !important;
    }
}
```

**Comment by overdodactyl** [comment]
Ah! Good catch, tested it in my userContent.css, moved it to it's own file and forgot to add the import.  Should be added now, thanks :)

That's odd I'm not seeing the labels, must be an OS specific thing I guess?  Either way, I included the code you provided into `library.css`,  so it should be fixed for everyone, appreciate that!
