### ISSUE TITLE
Alternative versions of userChrome/Content

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#59]
Can you please make a version that doesn't have support for extensions/addons?

I don't use this theme to for extensions/addons so having all that extra code is useless and makes Firefox take more time to load the theme.

Thank You :)

**Comment by overdodactyl** [comment]
That's a good idea, thanks! :)

The version you will want to use now is in a the new directory [alternative_user_files](https://github.com/overdodactyl/ShadowFox/tree/master/alternative_user_files) and called `userContent_no_addons.css`.

For anyone curious, the new gulp task for this is called `userContent_no_addons` and can be run using:

`gulp userContent_no_addons`

Additionally, it is now a dependency of the gulp task `userContent_all` (i.e. whenever `gulp userContent_all` is run, both the complete version and the version without addons is created).

I'm going to go ahead and change the name of this issue and leave it open for a little while.  If anyone has any other alternative versions of either userChrome or userContent, feel free to let me know and I will add them.

**Comment by qazip** [comment]
Would the opposite of this issue be possible? Make a version only for web-extensions and not anything else? (I find the native dark theme of firefox pretty good already and I don't go to about:pages all that much, so it's really not necessary that code.)

**Comment by overdodactyl** [comment]
It would definitely be possible/easy to do.  I do wonder if this would be a great approach to take, however.  I imagine there are a lot of styled extensions that you don't use.  So if your goal is to eliminate unnecessary code, this wouldn't completely do that.  

Maybe using a custom version of `userContent_imports.css` would be the best way to go?
