### ISSUE TITLE
Extensions with compatibility issues in about:addons - please list here

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#6]
Some extensions that have preferences built into the addon page utilize their own css files and don't use all the Firefox default styling settings.

As such, compatibility issues or ugly appearances may arise.  

Please see the update [here](https://github.com/overdodactyl/userContent-tweaks#important-update-11292017).

If you run across any addons with this issue, please list them here and I will get out a fix when I can.

In addition, please mention the addon as either (1) compatibility - text unreadable or (2) ugly design.

As always, if you are willing/able to help create a fix for an addon, please submit a pull request or post the code somewhere and link to it here.  Not much goes into each fix, but I am only one person and we don't all use the same extensions. See [here](https://github.com/overdodactyl/userContent-tweaks/tree/master/webextension-tweaks) for addons that have currently have fixes and for a general idea on how to create a fix yourself.

**Comment by chinook77** [comment]
Wrong background on this addons:
1) Checker Plus for Gmail:
wrong
![screenshot 33 _li](https://user-images.githubusercontent.com/19517348/33530928-1223a60c-d865-11e7-8acc-8633334be2f6.jpg)

correct
![screenshot 35 _li](https://user-images.githubusercontent.com/19517348/33530902-af31b73c-d864-11e7-9654-d7ccb1b8be94.jpg)

2) Checker Plus for Google Calendar:
wrong
![screenshot 32](https://user-images.githubusercontent.com/19517348/33530931-20b37d1e-d865-11e7-934a-ed418b62ac51.png)

correct
![screenshot 34](https://user-images.githubusercontent.com/19517348/33530943-4d888f14-d865-11e7-8b44-4192f745d585.png)

Thanks in advance.

**Comment by overdodactyl** [comment]
Hi @chinook77, thanks for the report on these extensions.  Turns out I needed to make a change to `dark_nav_bar_menus.css` to prevent extensions from using the dark theme.  Please let me know if this resolves things for you.

**Comment by chinook77** [comment]
Hi, thanks for your work. The add-on background issue is fixed, but this separator in not longer visible.
Before:
![screenshot 38 _li](https://user-images.githubusercontent.com/19517348/33581356-57ed1b44-d92f-11e7-9570-ecaf8992572f.jpg)

After:
![screenshot 37 _li](https://user-images.githubusercontent.com/19517348/33581374-62e6671c-d92f-11e7-9a15-d2c48277a2f9.jpg)

**Comment by overdodactyl** [comment]
I'm glad that fixed it.

For better or worse, that was a design choice on my part (perhaps I should have left it alone as it's primarily a personal preference).

If you would like it back, delete the line containing `@import "userChrome-files/remove_bookmarks_bottom_border.css";` in you userChrome.css file.

**Comment by chinook77** [comment]
Thanks for your time.

**Comment by SonicBlader** [comment]
Hi!

The Dark Mode (WebExtension)'s page is not legible.

https://i.imgur.com/hb54NWK.png

https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/?src=userprofile

**Comment by Sporif** [comment]
Tree Style Tab's debug options are unreadable. This would fix it:

```
#debug-configs {
    color: var(--primary-light-color) !important;
}
```

**Comment by overdodactyl** [comment]
Thanks @Sporif! Fix is now included

**Comment by overdodactyl** [comment]
@SonicBlader, a fix for SonicBlader is now included

**Comment by crkellen** [comment]
Hi, I may have a chance to try and solve this myself, but currently I haven't delved too deep into it.

### These have issues with the about:addons page:
[Tab Suspender (memory saver)](https://addons.mozilla.org/en-US/firefox/addon/tab-suspender-tab-unloader/)
[Smart HTTPS (revived)](https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/)

Their config options when you click "More" on the about:addons page are nigh unreadable.

### These addons could be enhanced by having a dark mode (when clicking their icon):
[uMatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/)
[Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/)
[Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)

**Comment by overdodactyl** [comment]
Thanks @crkellen! 

I've started working on Multi-Account Containters...let me know if you get any of the others!

**Comment by crkellen** [comment]
I'll be seeing if I can get Tab Suspender tomorrow, I'll let you know how it goes!
null

**Comment by overdodactyl** [comment]
@crkellen, I uploaded my "first draft" of Multi-Account Containers yesterday if you want to give it a look.

I might try and tackle uMatrix next

**Comment by crkellen** [comment]
That was fast! Sounds awesome! Do you happen to know how to modify the colored bar that Multi-Account Containers puts on individual tabs?
I solved an issue I had with another edit I made in a roundabout way as I didn't know if I could access those colors.
I don't have much time during weekdays, but I'll try to look at it tonight and see if I notice any issues.
null

**Comment by overdodactyl** [comment]
>Do you happen to know how to modify the colored bar that Multi-Account Containers puts on individual tabs?

I think you can do this from the extension itself.  If you go to Edit Containers then chose the one of interest, you can use any of these colors:

![container_colors](https://user-images.githubusercontent.com/33071129/34578088-9ce8cebe-f17b-11e7-922a-9f080462f8f6.png)

Or are you hoping to add different colors that aren't available by default?

And don't stress about giving it a look if you don't have time, just let me know whenever if you run across any issues :)

**Comment by crkellen** [comment]
Sorry,should have specified my reason for wanting to edit.I would show an example but I am at work. Basically, I wanted to reduce the width of the colored bar, as it was wider than the size of my pinned tabs on the Tree Style Tab bar I setup.
Specifically you can see it in this screenshot I have: https://media.discordapp.net/attachments/279508609988296705/397251682007908373/Capture.PNG?width=639&height=520
In the top left you can see bits of the highlight (purple, green) hanging off the side. I spent a day attempting to fix this when I finally just settled for making the borders circles using the `border-radius` attribute, which hides the issue.
null

**Comment by overdodactyl** [comment]
Oh interesting!

I'll give it a look when I get the chance!

**Comment by crkellen** [comment]
My current implementation is working fine enough, so don't worry if you can't figure it out quickly, it's very minor.
I do appreciate the quick work you do however.
null

**Comment by overdodactyl** [comment]
Sounds good! And thanks, I appreciate that :)

**Comment by crkellen** [comment]
Oh wow that was fast. I'll be sure to check them tomorrow after work.
null

**Comment by overdodactyl** [comment]
Also add first drafts of Cookie AutoDelete and uMatrix if you want to give them a try at any point!

**Comment by crkellen** [comment]
Okay, Cookie AutoDelete works great, Tab Suspender works great, uMatrix settings are much better, but the main interface still needs work, however, I know that's also the case with uBlock Origin as you need to style it in a way that is still okay for color blindness. However, in both uBlock Origin and uMatrix there are splotches of white in the background (uBlock bottom right, uMatrix top right). Smart HTTPS doesn't seem to have been changed at all. I'll do a double check to make sure I got it right.

**Comment by overdodactyl** [comment]
Thanks for the feedback @crkellen! Could you possibly grab a screenshot of the white areas in uBo/uMatrix you're talking about?  I'm not sure I'm getting them:

![umatrix](https://user-images.githubusercontent.com/33071129/34635772-1bb9b062-f28c-11e7-90b8-ef8d270ba352.png)

![ublock2](https://user-images.githubusercontent.com/33071129/34635774-1f58b510-f28c-11e7-9fce-4eeae0487dbd.png)

>Smart HTTPS doesn't seem to have been changed at all

I'll double check with Smart HTTPS, but that screenshot above is what I was seeing (I'll re-install and check though)...are you looking for changes in about:addons or the popup?

**Comment by crkellen** [comment]
Yes, it is that white spot. Here are the images. Smart HTTPS does not work for either the main interface or the about:addons page.

![ublock](https://user-images.githubusercontent.com/6870231/34635979-2ac86794-f25d-11e7-86d4-ed12db114cb2.png)
![umatrix](https://user-images.githubusercontent.com/6870231/34635980-2d023648-f25d-11e7-9985-72e8c7ee92e8.png)
![smarthttps1](https://user-images.githubusercontent.com/6870231/34635982-31bd3a8e-f25d-11e7-99e4-e43d4169559f.png)
![smarthttps2](https://user-images.githubusercontent.com/6870231/34635983-3339817e-f25d-11e7-904e-358b54d57271.PNG)

**Comment by overdodactyl** [comment]
Hmm.

The uBO one is a little puzzling to me, I'm not sure what would be causing that to be styled on some computers and not others.  I'll have to see if a can get a hold of a Windows computer to check it out.

uMatrix I can see a number of differences in our screenshots (white spots, darker background, blue label etc).  Are you on the latest version of the repo? I'm also curious about this for uBO, as it looks like you have grey noop rules, which I had changed to blue to stand out from the background.

The other possibility is that the UI was changed in one of the more recent updates (I tested on uMatrix 1.2.0, and I see you're using 1.1.2

The Smart HTTPS settings are a little odd as well...just reinstalled, changed the internal UUID and it seemed to work fine.  I'll give it a closer look though.  As for the popup I hadn't done that, just had done the settings, so I'll do that as well.

**Comment by crkellen** [comment]
Ah, I realized something. I always forget that I'm still on Firefox Beta. That may be the cause,along with different versions of the add-on.
null

**Comment by overdodactyl** [comment]
I don't think that should matter in this case since it's the extensions getting styled, but I'll test on different versions (I admittedly often forget I'm generally on Nightly as well).

**Comment by crkellen** [comment]
I just updated uBlock to the latest release (9 hours ago), and uMatrix to the latest as well (1.2.0). 
Additionally, do you know if it is possible to style the small popup that Cookie AutoDelete makes when it deletes cookies?

**Comment by overdodactyl** [comment]
And just to double check, are you on the latest updates of ShadowFox?

I'll give the CAD popup a look

**Comment by crkellen** [comment]
Oh yes, forgot to mention, I pulled down the repo about 3 minutes before posting my first message.
null

**Comment by overdodactyl** [comment]
Right on.  One last question before I stop buggin' ya:

What version of userContent are you using? The combined one or the one with all the import statements?

**Comment by crkellen** [comment]
I use the "gulp userContent_all" command after changing all my add-on files to use my internal id
null

**Comment by overdodactyl** [comment]
Sounds good, thanks!

I'll get back to ya after looking into it a bit more.

**Comment by overdodactyl** [comment]
@crkellen,

I've made a few changes that will hopefully fix some of the issues you mentioned.  Still not sure on others though...

Let me know what still needs work

**Comment by crkellen** [comment]
Thanks, I will review this tomorrow.
null

**Comment by crkellen** [comment]
I apologize for the delay. I recently moved Saturday and don't have internet unlike likely later today. If you can, please also look into the following, I'm sorry I was unable to get pictures.
Multi-Account Containers:There's a screen that pops up if you do the following:1.open a container tab other than default.2. Navigate to a webpage.3. Click the add-on icon and set this page to always open in that container.3. Close the tab.4. Open a second, DIFFERENT container, that is not default.5. Go to the same webpage.6. A white page will appear asking if you want to open the page in the container you set earlier.
uMatrix:When uMatrix detects that a URL is sending you to a domain that is blocked, such as an ad-domain, it will display a page with information that was blocked. The information is not styled, the background of the page is.
You can test that one by going to pcpartpicker.com and going to any part, then clicking the link to a website to buy it at like Newegg.com
null

**Comment by overdodactyl** [comment]
No worries! And they should both be fixed now - for Mult-Account Containers you'll have to add the Internal UUID in a second place

**Comment by crkellen** [comment]
Okay, finally got around to doing this. uMatrix and uBlock Origin are both the same as the above screenshots. Likely, it's a difference between Firefox 58 and 59.

However, both of the above listed issues (uMatrix and Multi-Account Containers having separate webpages) are fantastically fixed.

**Comment by overdodactyl** [comment]
Thanks for giving it a look @crkellen! I'm glad the separate webpages all got fixed.

I checked uBO and uMatrix on FF 57-59, and it appears to be working for me in all cases, which makes me think this is due to a difference in OS...which unfortunately limits how much I can be of help.

I've added a new issue, #58, with a help wanted tag, so hopefully that will get a little more attention and someone can help me figure out what's going on there.

**Comment by crkellen** [comment]
Sounds good. It's not incredibly bad or anything and it's certainly still better than the alternative.
null

**Comment by eberhardweber** [comment]
The RSS reader add-on [Brief](https://addons.mozilla.org/en-GB/firefox/addon/brief/) currently clashes pretty badly with the dark theming. It has its own built-in option for modifying the CSS. Maybe someone could take a look at it?

**Comment by overdodactyl** [comment]
Hi @eberhardweber, I've added initial styling to Brief.  Change the Internal UUID in the normal manner, then add the following to the custom styling section:

```css
@import url("https://rawgit.com/overdodactyl/ShadowFox/master/webextensions/brief.css");
```

I don't use the addon, so I likely missed some things.  If that's the case, or you would like to see anything changed, just let me know.

**Comment by overdodactyl** [comment]
Hi all, it's becoming a little difficult to keep track of all requests and problems using only 1 issue for all extensions.  

As such, I'm going to go ahead and close this and ask that all new problems or requests be put into their own issue (one extension per issue).

For any lingering problems brought up here that I haven't addressed here, I would ask that you open up a new issue. 

I believe I have addressed most things here, so if I've forgotten something, that would be a good way to remind me anyways :)

@crkellen, regarding uBO and uMatrix, check out #58.  The problem is due to a FF bug (which has been marked as WONTFIX unless I can show it's not only a `userContent.css` problem), so I'm trying to figure out where to go from here...you might be able to help :)

@eberhardweber, if my styling of Brief wasn't complete, just open up a new issue with any suggested fixes.

**Comment by NSP-0123456** [comment]
I have issue with All-In-One-Sidebar background It still light for all the add-ons (extensions, themes, ...) and also from Sage++  extension..
