### ISSUE TITLE
about:newtab top sites tile buttons bug

### ISSUE THREAD

**Issue by ngoo5tsong5sik** [overdodactyl/ShadowFox#61]
![snipaste_2018-02-08_18-01-08](https://user-images.githubusercontent.com/16879992/35968168-0ec9d760-0cfe-11e8-8386-6eb25f00a879.png)

As the picture shows, the buttons are translucent and remain visible while unhovered.

Tested on Nightly 60.0a1 (2018-02-07, with imported CSS) and Developer Edition 59.0b7 (with a clean new profile and combined CSS) on Windows 10.

**Comment by overdodactyl** [comment]
Thanks @ngoo5tsong5sik! 

Should be fixed now - I changed their opacity as well as it's color and the border color on hover.    

I don't really use the new tab page options, so feel free to let me know if you would prefer a different look!
