### ISSUE TITLE
Updater Scripts

### ISSUE THREAD

**Issue by overdodactyl** [overdodactyl/ShadowFox#62]
This is a continuation of topics brought up in #19 and #36.

I've received a number of questions regarding installation, being able to customize the accent colors, changing the Internal UUIDs etc., and how have these changes carry over after updating to the latest ShadowFox version.  Most of these questions have come from people making use of just `userContent.css` and `userChrome.css` (i.e. not the imports versions or using any gulp tasks...which I'm guessing is about 90% of people).

To address this, I've created a simple bash script that will take care of (1) installation, (2) updating, and (3) overriding any color preferences or UUIDs.  The script is found [here](https://github.com/overdodactyl/ShadowFox/blob/master/ShadowFox_updater.sh).

In short, this script should be placed in your Firefox directory (*not* your chrome folder).  When ran, it creates a chrome folder if it doesn't exist.  Inside the chrome folder, if a userChrome.css and/or a userContent.css file exists, it backs them up.  Then, it downloads the latest versions from this repository.  Finally, it overrides any color variables or UUIDs defined inside the script.  

I'm hoping this will be of help.  If anyone has any suggested changes, different use cases you would like it to apply to (i.e. if you're using the import files, git, gulp, etc.), or anything else, feel free to let me know! This is just a first pass at it.

I've tested it on a Mac, and it *should* work on Linux I believe, but I am unable to test that (if anyone could let me know whether or not it works, that would be great).

~~Lastly, I'm hoping to find a Windows user that can help me write/test a Windows version of this script.  @CaptaPraelium would you still have time/be interested in doing so?~~ Never mind, @CarlColijn is helping out :)

**Comment by overdodactyl** [comment]
Thanks for testing it @mac1202!

The output is a little sloppy with `\n` being printed literally instead of used as a new line character.  I might need to change all my `echo` commands to `echo -e`'s to prevent that from happening.  

As for the actual progress of the script, it looks like it successfully backed up your `user*css` files, downloaded the latest versions of ShadowFox, but then failed variable replacements portion...is that correct?

**Comment by overdodactyl** [comment]
Looks like there's a difference between mac's and linux's syntax for sed.  `sed -i ''` replaces in place on mac, but on linux it tries to replace in a file name `''`.  

I've added a new version, specific for Linux [here](https://github.com/overdodactyl/ShadowFox/blob/master/ShadowFox_updater_linux.sh) if you don't mind giving that a try at some point :)

**Comment by mac1202** [comment]
This version seems to work properly.

**Comment by CaptaPraelium** [comment]
Finally got time to try this on windows. Works like a charm, including my custom stuff too. Also fixed the white background since ff60. Great, great, great.
