### ISSUE TITLE
about:performance text color issue

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#63]
Hi!
Using imports version, the text in the grey box is also grey and therefore only readable when selected.

![screenshot about:performance](https://user-images.githubusercontent.com/1388389/36148490-8f656d64-10bc-11e8-9a1b-79c8b9170801.png)

`Windows 7 x32`, `FF 58.0.2`, latest ShadowFox 

Thanks for your work!

**Comment by overdodactyl** [comment]
Thanks @stonecrusher! Should be fixed now :)
