### ISSUE TITLE
Dark theme for vim vixen

### ISSUE THREAD

**Issue by qazip** [overdodactyl/ShadowFox#64]
If you are submitting a feature request for a webextension, please include all relevant info, including:

* webextension name: vim-vixen
* link to the webextension in the AMO store: https://addons.mozilla.org/en-US/firefox/addon/vim-vixen/
* what needs to be styled (settings in about:addons, popup etc.)
I'd like to have the console in dark. For example, whenever you click "o", a console opens. Having that console as it currently is (white) is blinding. Having a dark version would be fantastic!

There's already an issue on their repo regarding this, but there doesn't seem to be much interest.. https://github.com/ueokande/vim-vixen/issues/161

Thank you very much in advance,

**Comment by overdodactyl** [comment]
Hi @qazip,

I've just added a "first draft" for vim vixen.  My goal was to give it a similar look to FF's develop tools/web console:

![vim_vixen](https://user-images.githubusercontent.com/33071129/36239380-f0b5a7e2-1200-11e8-9670-12e1db84705e.png)

I hadn't used the extension prior to doing this, so it's likely I've missed things.  I'll keep playing around with it and making changes as I run into things.  If you could give it a try though, let me know what you think and point out anywhere I haven't styled, that would be great!

**Comment by qazip** [comment]
wow, that was fast. I will let you know as soon as I figure out how to use the tweaks for webextensions but not anything else..

**Comment by qazip** [comment]
I finally understood how to make it work. I suggest adding a bold statement to the wiki, "Web-extensions will not work out of box, user interaction is needed", or something to that effect :D 

Regarding the theme, it's perfect for my needs! I'll let you know if something is not right! Thank you very much, you're awesome!

**Comment by dessalines** [comment]
That looks beautiful, any updates on this?

**Comment by overdodactyl** [comment]
Hi @dessalines! What type of updates are you hoping for?

The theme for vim vixen is included in the repo, and at a quick glance it seems to be alright.  Is there something not working for you?

**Comment by voloshyn** [comment]
I've tried ShadowFox with Vim Vixen, however, right after loading any page the content would quickly disappear and reappear. The "background flash" is almost instantaneous, but nonetheless frustrating.
I don't know the underlying reason, however removing "url-prefix(about:),"  from userContent.css solves the problem completely. 
I was never happier with internet browsing (ShadowFox+VimVixen+Dark Reader). 
Thank you very much!
