### ISSUE TITLE
How to disable changes to right-click context menu?

### ISSUE THREAD

**Issue by qazip** [overdodactyl/ShadowFox#66]
I find that the right-click menu of ShadowFox is way too small, I like the normal menu. It's already dark when one applies the dark theme provided by mozilla. How do I go about disabling just this thing?

I imagine it would be easier to have the default config and disable just this bit then to add everything else to an empty config.

**Comment by overdodactyl** [comment]
The easiest approach would probably be to use the `userChrome_imports.css` and `userContent_imports.css` files.  Then you can just comment out or delete the corresponding files you don't want included.  See here for more info:

https://github.com/overdodactyl/ShadowFox/wiki/Getting-Started#i-want-to-be-able-to-customize-shadowfox-i-do-not-want-to-use-everything-in-this-repository-or-i-want-to-make-significant-modifications-to-certain-files

**Comment by qazip** [comment]
Oh, the compactness of the context menu is exactly the problem. I'll close this issue and follow the other one, thank you!
