### ISSUE TITLE
[webextension] Neat URL settings need styling

### ISSUE THREAD

**Issue by tzimon** [overdodactyl/ShadowFox#68]
In some addons' settings pages of about:addons the font (or parts of it) stays black, so you can barely read it on the grey background. Examples for this are "Dark Mode", "Skip Redirect" and "Neat URL".

**Comment by overdodactyl** [comment]
Hi @tzimon, please give this section of the wiki a look:

https://github.com/overdodactyl/ShadowFox/wiki/Altering-webextensions

Looks like Skip Redirect and Dark Mode have fixes already available (if there’s been any changes in the webextensions making it no longer work, please let me know). 

I’ll look into getting a fix out for Neat URL

**Comment by tzimon** [comment]
Thank you! I didn't know about these additional fixes for addons. Should have read the readme file I guess.

**Comment by overdodactyl** [comment]
Neat URL should have a fix now.

If you run across any other problems, feel free to let me know! (one issue per extension, preferably :) )
