### ISSUE TITLE
html files shows dark background color

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#71]
If you create an empty .html file and open it, it will have dark background color.

I'm working on a website in a local folder and have to disable ShadowFox to be able to see the original background color of my website.

Is there a fix for this?

Thank You :)

**Comment by overdodactyl** [comment]
This was due to the themeing of directory listings (any url starting with `file:///`) that was introduced in #39. 

I've changed the `@-moz-document` qualifier to now match any url that starts with `file:///`, but doesn't end with `.html`. 

I think that should take care of this problem :)
