### ISSUE TITLE
Turn the HTTPS secure icon into Green rather than Blue.

### ISSUE THREAD

**Issue by SeriousHoax** [overdodactyl/ShadowFox#72]
The default green icon of Firefox or Chrome for the safe/secure HTTPS icon suits better. The Blue doesn't really suit.

**Comment by CaptaPraelium** [comment]
I like the blue.
I also have some custom CSS to turn the entire address bar blue, to highlight insecure sites.

**Comment by SeriousHoax** [comment]
Ohh I see. I'm actually used to the green color more. Green is easily noticeable.
Do you know any simple way to change the color to green?

**Comment by overdodactyl** [comment]
I like the blue simply for the consistency it provides.  I've just added a new variable for the secure connection color to make it easy to change, however.

If you're just using the full versions of userChrome.css and userContent.css, I would recommend running the new updater script that's located in the main repository from you Firefox profile. 

This will update you to the latest version of Firefox and create a folder called `ShadowFox_customization` inside your chrome directory.  Inside is a file called `colorOverrides.css`, which you can add the following to:

```css
--secure-connection-color: #12BC00;
```

after doing so, just run the updater again and restart your browser.  

The updater scripts are pretty new, so I haven't had time to write any documentation on them yet...hopefully I'll get that out today.

**Comment by SeriousHoax** [comment]
Thanks. It worked 🙂 btw, I didn't know about this script. So, every time I wanna update ShadowFox, I should just run the script and it will be updated?

**Comment by overdodactyl** [comment]
Yep!

Sorry for the lack of documentation, they've only been up for a little while :)

I'll get more info posted today, but here's the gist: any time you run it, it will back up your current userChrome/Content files (in case you need to revert back to them for whatever reason), download the latest versions from the repo, and insert any custom settings put in the `ShadowFox_customization` folder in their respective locations.

**Comment by SeriousHoax** [comment]
Ok, thanks. 
btw, just to be sure, I also use the following in my userChrome.css, 

@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
.tabbrowser-tab:not([pinned])
{
  max-width: 200px !important;
  min-width: 10px !important;
}
.tabbrowser-tab:not([fadein])
{
 max-width: 1px !important;
 min-width: 1px !important;
 max-width: 1px;
 min-width: 1px;
}


So, If I wanna keep this inside the ShadowFox userChrome.css then will pasting the above code inside the userChrome_customization.css work? (userChrome_customization.css is inside the ShadowFox_customization folder of course).

**Comment by overdodactyl** [comment]
That'll work! (I probably would get rid of the `@namespace` line though.)

Anything that's inside the `userChrome/Content_customization.css` files will get appended to the very end of ShadowFox's default userChrome/Content.  This way, every time you update, the setting there will go into effect and take precedent over anything ShadowFox sets (in other words, your custom settings always have a higher priority than the ones in the repo).

After adding the code to that file though, you will have to run the updater/restart your browser, however.

**Comment by SeriousHoax** [comment]
OK, got it. Perfect. Thanks a lot 🙂

**Comment by overdodactyl** [comment]
No problem! :)
