### ISSUE TITLE
Can't setup web extensions

### ISSUE THREAD

**Issue by barletta** [overdodactyl/ShadowFox#74]
Hi, thanks for such a neat theme for FF!

I'm having trouble setting up the updater (Mac). The script is in the correct folder and I can initiate it, however after manually chaging my UUID's and completing running the script it defaults back to not having an UUID. 

Thanks in advance

**Comment by overdodactyl** [comment]
Hi there! 

Glad you're enjoying the project :)

My apologies for the confusion and current lack of documentation for the updater scripts (I keep meaning to do so but get caught up with other work).

The updater scripts basically work by backing up your old userChrome/Content, downloading the new ones from the repo, then applying any customizations found in the `ShadowFox_customization` directory to the two files.

In the case of the UUID's, you'll want to make use of the file `internal_UUIDs.txt` file that was generated the first time you ran the updater.  In this file, you'll add one line per extension, in the following format:

`extensionName_UUID=internalUUID`

So, for example, lets say you have two extensions, uBlock Origin and Tree Style Tab.  In userContent.css, you'll see the strings to be replaced are `tree_style_tab_UUID` and `ublock_origin_UUID`.  Your `internal_UUIDs.txt` file should then contain two lines:

`
ublock_origin_UUID=72cc0bdd-b9ee-9d4a-b306-8d044cc4dd98
tree_style_tab_UUID=efb99b92-8e90-4041-a9a3-924049c1819a
`

(obviously replace the UUIDs with yours, however)

**Comment by barletta** [comment]
I'm sorry for the trouble but I'm not being able to make it work.

I've have added the four extension UUID's that I use (`cookie_autodelete`, `decentraleyes`, `https_everywhere` and `ublock_origin`) to the text file, re-run the script and still hasn't applied the changes. What am I missing?

**Comment by overdodactyl** [comment]
What does your text file look like?

**Comment by barletta** [comment]
```
cookie_autodelete_UUID=5ba7e258-ab98-d648-a941-19d366e39b5a
decentraleyes_UUID=fdb3f0b4-e463-7a4f-afcb-bd182e14d0be
https_everywhere_UUID=e5cd1b97-6cbe-3d4b-97ad-9dce2b62868c
ublock_origin_UUID=c34c43d6-47bd-0045-b10a-cfc9b0840376
```

**Comment by overdodactyl** [comment]
Hmm that all looks good.  I copy/pasted that and it worked as expected for me on a mac.

Is the updater script located in the root directory of your Firefox profile (not the chrome folder)?

Also, when you run the script, which message are you given:

```
You have not defined any internal UUIDs for webextensions.

If you choose not to do so, webextensions will not be styled with a dark theme and may have compatibility issues in about:addons.

For more information, see here:
https://github.com/overdodactyl/ShadowFox/wiki/Altering-webextensions`
```

or 

```
Your internal UUIDs have been inserted.
```

**Comment by barletta** [comment]
Yes, the updater is in the root folder and I get the second message! Any other info I can give you to pinpoint the problem?

**Comment by overdodactyl** [comment]
At the very least that should indicate the script is correctly locating your text file and recognizes it has content in it...

Can you open up `userContent.css` (in your chrome directory) and just search for `5ba7e258` and see if it's getting placed anywhere in the file?

**Comment by barletta** [comment]
It is. Result: `@-moz-document url-prefix("moz-extension://5ba7e258-ab98-c648-a941-19d366e39b5a/") `

**Comment by overdodactyl** [comment]
So that's what it should look like.  Are you sure you're using the right UUID's? Did you make sure to restart your browser?

**Comment by overdodactyl** [comment]
Strange.  Is it possible you're in a different FF profile?

Try adding 

```css
* {
  background: red !important;
}
```
to the very end of the file, restart the browser, open a few pages and see if everything's red.  That should tell ya if the right file's being used.

**Comment by barletta** [comment]
Doesn't affect anything. Is the folder looking ok to you? [screenshot](https://imgur.com/a/Fd2gI)

**Comment by overdodactyl** [comment]
That looks good.

Try the following:

* Go to `about:support` via the address bar

* Scroll down to the Profile Folder

* Click "Show in Finder"

    * This should open up a finder window with your profile highlighted

* Double click that folder to open it

Do you see your chrome folder there?

I'm wondering if it's possible that you put it in your local profile directory instead of the root one, or that you have multiple Firefox profiles and it's not in your active one.

**Comment by barletta** [comment]
It opened that "xmm..." folder that had a chrome folder in it too, so I dragged the script there (xmm folder) and runned it but had the previous error of `You have not defined any internal UUIDs for webextensions.`

**Comment by barletta** [comment]
I fixed it! You were right, I had to run it from that weird name profile folder and then I just replaced the text file where I previously added the UUID's. Now I just need to wait for Privacy Badger to be added to the list of supported add-ons. Thank you so much for your help and patience! Best of luck with this project mate, it's amazing!

**Comment by overdodactyl** [comment]
Glad you got it working :) Sorry for any confusion!  

>Privacy Badger 

That's probably a good one to add.  While I don't use it myself, I know a lot of people do.  Feel free to open a new issue for it if you would like...that will keep kinda keep it in my cue of things to do and keep me from forgetting haha.

And no problem! Happy there's people making use of it
