### ISSUE TITLE
about:memory logs unstyled

### ISSUE THREAD

**Issue by elerch** [overdodactyl/ShadowFox#76]
* browser version: stable
* operating system: mac
* explicit instructions how to get to the broken feature/webpage
  Go to "about:memory". Click "Measure" button in upper left in the Show memory reports group. The resulting memory statistics will appear in the main area of the screen, similar to the screenshot.
* how you are using ShadowFox (complete userChrome/Content, userChrome/userContent_imports, gulp)
  I have shadowfox cloned in my Firefox profile directly.

<img width="1123" alt="screen shot 2018-03-03 at 1 46 04 pm" src="https://user-images.githubusercontent.com/226199/36939874-59ce3b74-1eed-11e8-8d70-7dcc3f557b5b.png">

**Comment by overdodactyl** [comment]
Hi @elerch, is your clone up-to-date with the repo?  These were style a little while back.  This is what it looks like for me on a mac:

![memory](https://user-images.githubusercontent.com/33071129/36939973-7281f224-1f32-11e8-8f3f-6b5a98a06173.png)

**Comment by elerch** [comment]
Good call - I should have pulled first. My bad...it looks great. Thanks!

**Comment by overdodactyl** [comment]
No worries! :)

**Comment by overdodactyl** [comment]
Just noticed from my screenshot there's something funky going on with the check boxes in the top options - re-opening until that's fixed
