### ISSUE TITLE
Consider adding addons.mozilla.org 

### ISSUE THREAD

**Issue by Sporif** [overdodactyl/ShadowFox#9]
userContent.css is the only way to theme AMO now.

**Comment by overdodactyl** [comment]
That's a good idea - definitely on my radar now. 

Thanks!

**Comment by overdodactyl** [comment]
Just want to let everyone know this is in the works, but it's going to take some time :) 

![amo](https://user-images.githubusercontent.com/33071129/33749625-b117d2b0-dbc6-11e7-903d-9eff6c29e7ea.png)

**Comment by overdodactyl** [comment]
It's not perfect yet - but ready enough for people to start giving it a look and providing some feedback I think :)

**Comment by CaptaPraelium** [comment]
Looking good. I am still using the old version of the AMO site as the new version does not allow to search by tags (among other limitations... ) Honestly I think the new version is a significant downgrade but I guess it's the only way that will work in the future so there's no point skinning the old site?

**Comment by CaptaPraelium** [comment]
It seems that the user-selected highlight colour is ignored here. Please refer to my other issue logged regarding about:* pages, this seems the same problem:

https://github.com/overdodactyl/userContent-tweaks/issues/15

**Comment by overdodactyl** [comment]
@CaptaPraelium 

> I am still using the old version of the AMO site [...] so there's no point skinning the old site?

I understand the frustration with the new site.  However, I think you are right that in time it will be the only available option.  I'm sure they will get will improve it with things like tags as well.  Given how much there still is to do on this project, I'm not sure I can prioritize the old site.  You may want to check out some old userstyles and see if they still work, for example, see #12.  

As always, if someone wanted to put something together and submit a pull request, I would incorporate it into the repo.

>It seems that the user-selected highlight colour is ignored here.

Where are you seeing this here?  In `amo_store.css`, all colors come from variables, so I'm not sure why this would be occuring here.

**Comment by imatimba** [comment]
For some reason the style is not applying for me, I'm using the repo directly as the chrome folder.  
Everything else works fine.  
amo_store.css and its import are present.  
Linux using KDE with Breeze Dark, not sure if it's relevant.

**Comment by overdodactyl** [comment]
Hmmm...

Is there any chance you're using an `http` version of the site?

`amo_store.css` uses `url-prefix("https://addons.mozilla.org")` so that could cause problems (didn't really think of that).

Granted, that's kind of a long shot guess

**Comment by imatimba** [comment]
I'm using https, if you try to go http mozilla forces https.  

![image](https://i.imgur.com/u13WSst.png)  

![image](https://i.imgur.com/Bk6HcnU.png)  

Git log just to make sure I'm in the latest commit:  

```
commit 85c98fb7826f594efaa134249f10fd980577e409 (HEAD -> master, origin/master, origin/HEAD)
Author: overdodactyl <pjohns33@protonmail.com>
Date:   Fri Dec 8 10:44:49 2017 -0700

    Removed confusing second declaration of variables that may have caused users problems defining custom color schemes #14 #15

commit eedd55a23c736250b869adecfaf69067fbc6ac0d
Author: overdodactyl <pjohns33@protonmail.com>
Date:   Fri Dec 8 02:01:08 2017 -0700

    amo store search result fix 3

commit 153a5baec75ceee4d1b3e69ba1aadb32c42b05a2
Merge: a450ce0 cbbf974
Author: overdodactyl <pjohns33@protonmail.com>
Date:   Fri Dec 8 01:58:49 2017 -0700

    Merge branch 'master' of https://github.com/overdodactyl/userContent-tweaks

commit a450ce0c92e0ff0771bdb001d0a4fb5d1bd716ce
Author: overdodactyl <pjohns33@protonmail.com>
Date:   Fri Dec 8 01:58:34 2017 -0700

    amo store search result fix 3

commit cbbf974b233d42aaab3fd5a867ef084301568ccf
Author: overdodactyl <33071129+overdodactyl@users.noreply.github.com>
Date:   Fri Dec 8 08:21:06 2017 +0000

```

**Comment by overdodactyl** [comment]
@imatimba, I'm changing some things right now.  Should have an update later tonight and will check in to see if it fixed anything

**Comment by imatimba** [comment]
Still the same with the latest changes.  
If I put the code from amo_store.css directly into userContent.css and remove the import it looks like this:

![image](https://i.imgur.com/DATQFy5.png)

![image](https://i.imgur.com/SsWaiEZ.png)

Also, testing this inverted theme https://github.com/NiklasGollenstede/stylish/blob/master/mozilla-org-inverted.css  
It works fine if it's on userContent.css, it doesn't load if I put it on amo_store.css replacing your code.

**Comment by overdodactyl** [comment]
Thanks for the update @imatimba.

That sounds like some really odd behavior (even those screenshots don't look quite when imported into userContent.css)

I would if I have some conflicting `@import` statements or something of that nature.

What OS are you on?

**Comment by imatimba** [comment]
Linux (Gentoo), KDE with Breeze Dark as theme.  
Tested other themes just in case but it's the same.

**Comment by overdodactyl** [comment]
Do you have any other custom userContent.css tweaks anywhere or just using this repository? (Wondering if it would be worth testing in a new profile)

**Comment by imatimba** [comment]
Just this repository, and I tested a clean profile in my second message.  
I'll try testing it in a VM with another distro, just in case it's some weird problem with Gentoo.

**Comment by overdodactyl** [comment]
> tested a clean profile in my second message

Sorry, forget you already mentioned that!

Let me now if that does anything - if not, back to the drawing board for me haha

**Comment by overdodactyl** [comment]
@imatimba, I made some changes to the way the repository was structured where the color scheme was being imported from.

Let me know if it works now

**Comment by imatimba** [comment]
Still the same, but adding amo_store directly into userContents works fine now. Except the buttons like "Add to firefox" that are blue.  

![image](https://i.imgur.com/3goL9rr.png)

I'll test on other distros later tonight or tomorrow.

**Comment by overdodactyl** [comment]
Let me know what you come up with - I don't know why that's happening for you :/

As for the buttons, those were overlooked on my part.  

Will fix ASAP

**Comment by CaptaPraelium** [comment]
I noticed a bit of an oddity but I suspect you're in the midst of fixing it with a couple of commits in the past minutes. I'll paste the images here for your reference:

Mouse out of box:

![image](https://user-images.githubusercontent.com/22152831/33800790-04bd5eae-dd9c-11e7-9749-cb9c556af853.png)

Mouse over:

![image](https://user-images.githubusercontent.com/22152831/33800794-16b10e76-dd9c-11e7-820b-16782947380c.png)

Clicked, mouse over:

![image](https://user-images.githubusercontent.com/22152831/33800798-29a0d4bc-dd9c-11e7-9f1a-0ba4811c323b.png)

Clicked, mouse out:

![image](https://user-images.githubusercontent.com/22152831/33800799-3b36c4e8-dd9c-11e7-8779-4b8a822b8806.png)

When it comes to issues like this, honestly, it does not bother me in the slightest. I thought you might like to know, though. Sorry to be a pain!

**Comment by overdodactyl** [comment]
@CaptaPraelium thank you for these!

And honestly, you're not being a pain at all :) I appreciate the help and feedback!  The more the marrier.  

Working on a lot of different pages, so sometimes it's way too easy to overlook things like tha

**Comment by imatimba** [comment]
Well, same thing on Ubuntu and Fedora.

![image](https://i.imgur.com/qKEHk9d.png)

![image](https://i.imgur.com/Eeh7UbA.png)

Windows 10 works fine, so it seems like it's an issue specific to Linux.

**Comment by overdodactyl** [comment]
Hi @imatimba,

I've taken a new approach to creating the userContent.css file - all changes are now included in `userContent.css` (see [here](https://github.com/overdodactyl/ShadowFox/wiki/Customizing-what-tweaks-are-included-in-your-userChrome-Content-files for how to customize which files are used).

Please let me now if this fixes everything for you

**Comment by overdodactyl** [comment]
Now that AMO is styled and hopefully a working solution has been found for Linux users, I think this can be closed.  

Feel free to open up a new issue with any problems/inconsistencies found on the site.
