### ISSUE TITLE
Automatic installation to profile folder

### ISSUE THREAD

**Issue by Shourai** [overdodactyl/ShadowFox#91]
I have to think about issue #84 a little longer to come up with some suggestions which might be good to implement.

On the other hand, I was thinking about automatically "installing" ShadowFox under the default profile.
This would work if the user want their `*.default` profile to be the one where ShadowFox is applied to
which I think will be the case for most people, and those who don't will have more knowledge about
profiles and can adjust accordingly.

Something I use for example would be
```bash
profileID=$(ls "$HOME/Library/Application Support/Firefox/Profiles" | grep default | sed -n 's/\([[:alnum:]]*\).*/\1/p')
profile="$HOME/Library/Application Support/Firefox/Profiles/$profileID.default"
```
Now you have the path and profileID of the default profile, with which we can
adjust the mac updater script so the user only needs to download the updater script
and everything will be installed automatically.
Everything would only have to be prepended by $profile.
What do you think?

I would assume it's similar on linux, don't know about windows.

p.s.: I am learning a tonne on the regex department because of this project, thanks! haha

**Comment by overdodactyl** [comment]
Really like the idea!

That would really help simplify things.


Maybe we could expand it a bit by doing the following?  

* Check if the script is already inside a profile 

    * If yes, continue to install in the current one (this would ensure no "breakage" occurs for people who already have the script installed in a profile other than default and might be nice for people using multiple profiles)

    * if not:

        * Do a quick check in `~/Library/Application Support/Firefox/Profiles/`

            * if there's only one profile, automatically install in that one

            * if there's multiple, print out the profile names and ask the user which to install in

And I really appreciate all the regex help you've provided :)

**Comment by Shourai** [comment]
Those additional checks are a good idea!
That should make updating/installing easier and smoother.

Also I think it would be a good idea to merge the linux/max updater scripts, they are quite similar.
For mac/linux specific commands one could use an if statement to check it's `uname`
```bash
if [ "$(uname)" == "Darwin" ]; then
    # Do something under Mac OS X platform        
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Do something under GNU/Linux platform
fi
```

**Comment by overdodactyl** [comment]
Great idea!! I didn't think of doing that.  The sed commands are (I think?) the only difference that I had to deal with

**Comment by Shourai** [comment]
I did a few simple tests using `gsed` and it appears that `sed` under Darwin is a subset
of `gsed` and the commands that work under Darwin should work on Linux (not vice-versa!).
What `gsed` has some extensions, see 
https://www.gnu.org/software/sed/manual/sed.html#BRE-syntax which mentions e.g.
`\+  As *, but matches one or more. It is a GNU extension`.

**Comment by overdodactyl** [comment]
The only one that I was getting stuck on was replacing "in place"

`sed -i ''` replaces in place on mac, but on linux it tries to replace in a file named `''`

I don't currently have a linux distro to test on, so I've only been able to go off what I found online and some error codes someone provided me when I originally had the two scripts together in #62.

Thanks for the link! I'll give it a look

**Comment by Shourai** [comment]
I'll also have a look into `sed -i` and report back if I found something interesting, haven't used that before.
I don't have a linux distro around either, so can't test it on that unfortunately.

**Comment by overdodactyl** [comment]
Looks like this might be the way to go for `sed -i`:

https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

**Comment by Shourai** [comment]
Just stumbled upon on the same solution!
```
sed -i.bak '/--start-indicator-for-updater-scripts: black;/,/--end-indicator-for-updater-scripts: black;/{//!d;}' userContent.css
```
creates `userContent.css.bak`
and at the end of the script just remove those files
```
rm userContent.css.bak
```.
Well that at least makes it compatible across both platforms!

**Comment by overdodactyl** [comment]
According to one of the comments there it has to be `sed -i.bak -e 's/foo/bar/' filename` for at least macOS Sierra and higher.

Would have to find out if that also works on LInux and pre-Sierra OSs.  

Might be best to just use the `if` statements you provided earlier and be safe if we can't test across all the OSs and versions

**Comment by Shourai** [comment]
Currently I am on high sierra and I don't need the `-e` flag.
``` bash
sed -i.bak '/--start-indicator-for-updater-scripts: black;/,/--end-indicator-for-updater-scripts: black;/{//!d;}' userContent.css
```
works fine for me.

**Comment by overdodactyl** [comment]
Interesting it works on high sierra - wonder it that user was just wrong or something was just changed from sierra to hs.  Either way, let's go with the if statements I think.  Better safe than sorry and I don't think that'll be a huge problem.

**Comment by overdodactyl** [comment]
Thanks! On a random note:

I've been considering creating a [Slack](https://slack.com/) or [Keybase](https://keybase.io/) group (or something similar) for this project...might be a nice place for convos like this/sharing code snippets without blasting people's email who are "watching" the repo haha.  

Do you use anything of the sort/would that be of interest to ya? Or prefer sticking GitHub?

**Comment by Shourai** [comment]
I am slightly familiar with Slack so I could join your channel.
Otherwise Discord or IRC would also work for me :)

**Comment by overdodactyl** [comment]
I've used Slack a little (not a ton), but haven't used IRC or Discord.  I'm *guessing* the latter two are a bit more popular though...seem to hear them pop up pretty often.

Any preference/suggestion?

**Comment by Shourai** [comment]
We could use Slack for starts and see how well that goes, could always decide to migrate if it doesn't work out.

**Comment by overdodactyl** [comment]
[Here's](https://join.slack.com/t/shadowfox-workspace/shared_invite/enQtMzI5Nzk5OTk1MjcxLThkMDgwOGE5ZDY1MDUyNjIwNWQ2MTlmMjEwZTJiZmZjYTUxODM4ZTRkNzhiNGRhZTFhMjdjMTFjMTQ3YjZjYzU) the invitation link for anyone who would like.  I'll get it added to README.md file shortly
