### ISSUE TITLE
Preferences dropdown needs border or different background color

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#93]
The dropdown blends with the background, which in some dropdowns gives the strange impression that there are no further items selectable. You will realize later when hovering it.

![screenshot 92](https://user-images.githubusercontent.com/1388389/37336688-74e63426-26b2-11e8-8846-a4fc8601213d.png)

FF 58.0.2 (64-Bit)

Sorry for writing so short, don't have much time atm

**Comment by overdodactyl** [comment]
I *think* this is also fixed behind a `@media` statement.  Let me know if it's still problematic in 59

**Comment by stonecrusher** [comment]
Updated to 59 and updated shadowfox.
Dropdown now has a black border so it works now.

![screenshot 93](https://user-images.githubusercontent.com/1388389/37373674-db29a1d6-2717-11e8-8c24-34cf6315d75b.png)


But actually in my eyes it still could be a bit clearer by either making a bright border instead of black on grey or making the background another color as the surrounding background. Highlight/hover color is different (blue) anyway.

**Comment by overdodactyl** [comment]
Agreed...that could look a lot better.  I'll see what I can do!

**Comment by overdodactyl** [comment]
Colors have been changed to match the normal context menus.  Let me know if that didn't work

**Comment by stonecrusher** [comment]
Changed colors look well in FF59 and 61(nightly). :+1:

**Comment by overdodactyl** [comment]
Good to hear - thanks for the report!
