### ISSUE TITLE
Bug in home page text

### ISSUE THREAD

**Issue by tsunami2311** [overdodactyl/ShadowFox#94]
![bugs](https://user-images.githubusercontent.com/12301593/37363629-c3ee7eae-26ce-11e8-8676-fd8a5834bb51.png)

FF59

Text is not read able under search bar.  reverting back to earlier verisons fix this,

**Comment by overdodactyl** [comment]
Are you sure you are using the latest version of ShadowFox?  This is what the newtab/home page looks like for me if I remove all the pocket/activity stream stuff:

![home_page](https://user-images.githubusercontent.com/33071129/37364432-7074dd62-26f2-11e8-9bf2-61c39c7c85f4.png)

Or is that a different page you are talking about?

**Comment by tsunami2311** [comment]
oh sorry i forgot, I set 58 and higher firefox to use the old start page give me sec to find the about:config for it

**Comment by tsunami2311** [comment]
browser.newtabpage.activity-stream.enabled

this set to false should make your homepage look like mine

**Comment by overdodactyl** [comment]
Thanks! Should be fixed now
