### ISSUE TITLE
How/Where do i include my own changes?

### ISSUE THREAD

**Issue by Vikijaka** [overdodactyl/ShadowFox#96]
Hello there,

i am sorry for posting this, but i need to ask how/where do i include/change my own customizations?
at  userChrome i had 

```
.tabbrowser-tab:not([pinned]) {
		max-width: 140px !important;
		min-width: 20px !important;
	}
```

userContent
```
@-moz-document url("about:newtab"), url("about:home"), url("about:*") {
    .activity-stream {
		background-color: #111 !important;
	}
     .tabbrowser-tab:not([pinned]) {
		max-width: 140px !important;
		min-width: 20px !important;
	}
}
```

I wasn't able to figure out which one worked, so i stayed at both before using "ShadowFox"
Well... where do i need to include the proper code to change the size a the tabs?
Editing the new files nor the files at the ShadowFox_customization folder are working for me.

I didn't know much about css coding, especially since stylish wasn't working prior FF changes with 56/57

Win 10 @ FF, beta channel (v59)

**Comment by overdodactyl** [comment]
Hi there,

I would recommend using the available updater scripts.  When you run it for the first time, it will create a directory titled `ShadowFox_customization` within your `chrome` folder.  Inside that folder you'll find `userContent_customization.css` and `userChrome_customization.css`.  You can add any personal tweaks to these files, then run the updater script again.

**Comment by Vikijaka** [comment]
> then run the updater script again.
> 

Thank you, that was the missing part.
